//! Thin async wrapper around the Resin sidecar control-plane REST API.
//!
//! Path A uses the Resin Go binary as the production proxy runtime and lets it
//! own the SQLite state (platforms / accounts / leases / subscriptions).
//! This client is the Rust-side forwarder the IPC commands layer uses to
//! talk to the sidecar admin REST API. It is constructed from a (api_base,
//! admin_token) pair captured in the Tauri shell from
//! `src-tauri/src/sidecar.rs::SidecarHandle` and never exposes the token to
//! the webview (AGENTS 7.6).
//!
//! Ponytail: this is a small reqwest wrapper, not an SDK. We do NOT model
//! every Resin REST endpoint. We expose only the verbs the IPC commands
//! layer currently needs:
//!   - POST /api/v1/platforms               create_platform
//!   - GET  /api/v1/platforms               list_platforms
//!   - GET  /api/v1/platforms/{id}           get_platform
//!   - DELETE /api/v1/platforms/{id}         delete_platform
//!   - GET  /api/v1/metrics/realtime/leases active_leases
//! Any request body is accepted as serde_json::Value so the caller can pass
//! exactly what the React form produced. We provide one canonical helper
//! (create_platform_from_name) for the common single-name path.
//!
//! Resin design notes:
//!   - Admin API token goes in `Authorization: Bearer <admin_token>`.
//!   - /healthz is the only unauthenticated endpoint (the safety-net uses it).
//!   - All admin endpoints are under /api/v1/*.
//!   - Path parameters ({id}) are URL-encoded: the spec validates platform_id
//!     as a canonical UUID so encoding is a no-op in practice, but we encode
//!     defensively in case a caller passes a non-canonical form.

use std::sync::OnceLock;
use anyhow::{anyhow, Context, Result};
use serde_json::Value;
use url::Url;

/// Loopback-only connection to the Resin sidecar admin REST API.
///
/// The `base` URL MUST always resolve to 127.0.0.1 (it is constructed from
/// SidecarHandle::api_base() which is always http://127.0.0.1:<port>). The
/// admin_token is the per-session secret generated by boot_resin; it NEVER
/// crosses the IPC boundary into the webview.
#[derive(Clone)]
pub struct ResinClient {
    base: Url,
    admin_token: String,
    http: reqwest::Client,
}

const API_PREFIX: &str = "/api/v1";

/// T15-4: Shared reqwest::Client reused across all ResinClient instances.
/// The IPC layer constructs a fresh ResinClient per call (one per Tauri
/// command), but reqwest::Client owns a connection pool + TLS context.
/// Reusing a single Client avoids building a new pool per IPC call.
/// Ponytail: std::sync::OnceLock (Rust stdlib, zero new deps).
static SHARED_CLIENT: OnceLock<reqwest::Client> = OnceLock::new();

fn shared_client() -> &'static reqwest::Client {
    SHARED_CLIENT.get_or_init(|| {
        reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(8))
            .build()
            .expect("resin_client: cannot build shared reqwest::Client")
    })
}

impl ResinClient {
    /// Construct a new client from a 127.0.0.1 base URL + admin token.
    /// We reject non-loopback bases defensively even though the only caller
    /// (boot_resin) already guarantees a loopback base.
    pub fn new(base: &str, admin_token: String) -> Result<Self> {
        let url = Url::parse(base).context("resin_client: invalid base URL")?;
        let host = url.host_str().unwrap_or("");
        let loopback = matches!(host, "127.0.0.1" | "localhost" | "::1" | "[::1]");
        if !loopback {
            return Err(anyhow!(
                "resin_client: base host '{host}' is not loopback; rejected (SSRF guard)"
            ));
        }
        // T15-4: reuse the shared reqwest::Client (connection pool + TLS).
        let http = shared_client().clone();
        Ok(Self {
            base: url,
            admin_token,
            http,
        })
    }

    /// Return a copy of the admin token for the safety-net poller (which for
    /// /healthz does not need it, but keeps consumers honest about scope).
    pub fn admin_token(&self) -> &str {
        &self.admin_token
    }

    /// Compose an absolute URL on the /api/v1 prefix.
    fn url(&self, path: &str) -> Result<Url> {
        let trimmed = path.trim_start_matches('/');
        let full = format!("{API_PREFIX}/{trimmed}");
        self.base.join(&full).context("resin_client: join failed")
    }

    /// Send an authenticated admin request and return the parsed JSON body.
    /// For non-success (2xx) responses we surface the upstream status + a
    /// short body excerpt rather than swallowing the error.
    /// T2-8 (ADR-0018): Read-only auto-retry wrapper. Calls send() and
    /// retries up to READ_MAX_RETRIES times with READ_RETRY_DELAY_MS between
    /// attempts. Only for GET methods (read-only); write methods use send()
    /// directly. Retries on network error or 5xx (server transient failure);
    /// does NOT retry on 4xx (client error) or success.
    async fn send_read(
        &self,
        path: &str,
    ) -> Result<Value> {
        let max_retries = 2u32;
        let delay = std::time::Duration::from_millis(500);
        let mut last_err = None;
        for attempt in 0..=max_retries {
            match self.send(reqwest::Method::GET, path, None).await {
                Ok(v) => return Ok(v),
                Err(e) => {
                    let s = format!("{e}");
                    // Retry on network errors or 5xx; don't retry 4xx or parse errors
                    let should_retry = s.contains("request send failed")
                        || s.contains("-> 503")
                        || s.contains("-> 502")
                        || s.contains("-> 500")
                        || s.contains("-> 504");
                    if attempt < max_retries && should_retry {
                        tracing::warn!(
                            "resin_client: read retry {}/{} for {path} after: {}",
                            attempt + 1, max_retries, s
                        );
                        last_err = Some(e);
                        tokio::time::sleep(delay).await;
                        continue;
                    }
                    return Err(e);
                }
            }
        }
        Err(last_err.unwrap_or_else(|| anyhow!("resin_client: exhausted read retries for {path}")))
    }

    async fn send(
        &self,
        method: reqwest::Method,
        path: &str,
        body: Option<Value>,
    ) -> Result<Value> {
        let url = self.url(path)?;
        let method_str = method.as_str().to_owned();
        let mut req = self
            .http
            .request(method, url)
            .header("Authorization", format!("Bearer {}", self.admin_token))
            .header("Accept", "application/json");
        if let Some(b) = body {
            req = req.header("Content-Type", "application/json").json(&b);
        }
        let resp = req
            .send()
            .await
            .context("resin_client: request send failed")?;
        let status = resp.status();
        if !status.is_success() {
            let txt = resp.text().await.unwrap_or_default();
            let excerpt = if txt.len() > 256 {
                format!("{}...", &txt[..256])
            } else {
                txt.clone()
            };
            return Err(anyhow!(
                "resin_client: {method_str} {path} -> {status}: {excerpt}"
            ));
        }
        if status == reqwest::StatusCode::NO_CONTENT {
            return Ok(Value::Null);
        }
        let ct = resp
            .headers()
            .get(reqwest::header::CONTENT_TYPE)
            .and_then(|v| v.to_str().ok())
            .unwrap_or("")
            .to_string();
        if ct.contains("application/json") {
            let v = resp
                .json::<Value>()
                .await
                .context("resin_client: json decode failed")?;
            Ok(v)
        } else {
            let txt = resp.text().await.unwrap_or_default();
            Ok(Value::String(txt))
        }
    }

    /// POST /api/v1/platforms
    /// body: free-form serde_json::Value (Resin accepts the fields described in
    /// DESIGN.md platform POST section); only `name` is required by Resin.
    pub async fn create_platform(&self, body: Value) -> Result<Value> {
        self.send(reqwest::Method::POST, "/platforms", Some(body))
            .await
    }

    /// Convenience: create a platform with just a name. Sticky TTL, filters,
    /// allocation policy left at Resin defaults.
    pub async fn create_platform_from_name(&self, name: &str) -> Result<Value> {
        if name.trim().is_empty() {
            return Err(anyhow!("resin_client: platform name cannot be empty"));
        }
        if name.len() > 253 {
            return Err(anyhow!("resin_client: platform name length > 253"));
        }
        // Resin V1: reject names with ./:|/\@?#%~ and whitespace. Mirror the
        // guard so the error message comes from us, not an opaque 400.
        const BAD: &str = ".:|/\\@?#%~";
        if name.chars().any(|c| BAD.contains(c) || c.is_whitespace()) {
            return Err(anyhow!(
                "resin_client: platform name contains disallowed char"
            ));
        }
        self.create_platform(serde_json::json!({ "name": name }))
            .await
    }

    /// GET /api/v1/platforms
    pub async fn list_platforms(&self) -> Result<Value> {
        self.send_read("/platforms").await
    }

    /// GET /api/v1/platforms/{id}
    pub async fn get_platform(&self, id: &str) -> Result<Value> {
        let path = format!("/platforms/{}", urlencoding(id));
        self.send_read(&path).await
    }

    /// DELETE /api/v1/platforms/{id}
    pub async fn delete_platform(&self, id: &str) -> Result<Value> {
        let path = format!("/platforms/{}", urlencoding(id));
        self.send(reqwest::Method::DELETE, &path, None).await
    }

    /// GET /api/v1/metrics/realtime/leases — active-lease snapshot used by the
    /// desktop Topology view in place of the dead resin-core LeaseTable.
    pub async fn active_leases(&self) -> Result<Value> {
        self.send_read("/metrics/realtime/leases")
            .await
    }

    /// GET /api/v1/metrics/snapshots/node-pool — global node pool snapshot.
    pub async fn node_pool_snapshot(&self) -> Result<Value> {
        self.send_read("/metrics/snapshots/node-pool")
            .await
    }

    /// POST /subscriptions - create a subscription. `source_type` is "remote"
    /// (with a `url`) or "local" (with `content`). The webview supplies the
    /// fields via a free-form JSON body; Resin fetches the nodes itself.
    pub async fn create_subscription(&self, body: Value) -> Result<Value> {
        self.send(reqwest::Method::POST, "/subscriptions", Some(body))
            .await
    }

    /// GET /subscriptions - list all subscriptions (raw array).
    pub async fn list_subscriptions(&self) -> Result<Value> {
        self.send_read("/subscriptions")
            .await
    }

   /// DELETE /subscriptions/{id} - remove a subscription (204 -> Null).
   pub async fn delete_subscription(&self, id: &str) -> Result<Value> {
       let path = format!("/subscriptions/{}", urlencoding(id));
       self.send(reqwest::Method::DELETE, &path, None).await
   }

   /// PATCH /api/v1/subscriptions/{id} - refresh a local subscription's content.
   /// Resin v1.2.0 exposes PATCH /subscriptions/{id} (HandleUpdateSubscription):
   /// a constrained partial-patch (NOT RFC 7396; null values rejected). The
   /// `content` field is allowed for source_type=local subscriptions; changing
   /// it triggers an async re-parse inside Resin. `source_type` is immutable
   /// after create, so the caller must NOT include it in the body.
   /// Used by T19-P2 node-pool per-group refresh button.
   pub async fn refresh_subscription_content(&self, id: &str, content: String) -> Result<Value> {
       let path = format!("/subscriptions/{}", urlencoding(id));
       let body = serde_json::json!({ "content": content });
       self.send(reqwest::Method::PATCH, &path, Some(body)).await
   }

   /// PATCH /api/v1/platforms/{id} - update platform fields (allocation_policy,
   /// regex_filters, region_filters, sticky_ttl, etc). Resin validates the
   /// body and returns 400 with a descriptive error for invalid enum values.
    /// Used by the topology canvas hot-switch (Phase R1/R2).
    pub async fn update_platform(&self, id: &str, body: Value) -> Result<Value> {
        let path = format!("/platforms/{}", urlencoding(id));
        self.send(reqwest::Method::PATCH, &path, Some(body)).await
    }

    /// GET /api/v1/nodes - list all proxy nodes (the "C category" ip channels).
    /// Resin paginates this endpoint (default limit < total); without an
    /// explicit limit the frontend gets a stale partial view while the node-pool
    /// snapshot grows. We pass an explicit limit (and optional offset) so the
    /// per-node table reflects the same count as the stats card.
    pub async fn list_nodes(&self) -> Result<Value> {
        self.send_read("/nodes?limit=500")
            .await
    }

   /// GET /api/v1/nodes?platform_id=<id>&limit=500 - the routable node list
   /// for a single platform (Resin DESIGN.md "list nodes" with platform_id filter).
   pub async fn list_nodes_for_platform(&self, platform_id: &str) -> Result<Value> {
       let path = format!("/nodes?limit=500&platform_id={}", platform_id);
       self.send_read(&path).await
   }

   /// POST /api/v1/nodes/{hash}/actions/probe-egress - on-demand egress probe
   /// (Resin v1.2.0 HandleProbeEgress). Requests cloudflare.com/cdn-cgi/trace
   /// through the node, returns {egress_ip, region, latency_ewma_ms}. Resin
   /// updates the node's egress_ip + TD-EWMA + routing as a side effect.
   /// Used by T19-P3 node-pool per-card probe button.
   pub async fn probe_node_egress(&self, node_hash: &str) -> Result<Value> {
       let path = format!("/nodes/{}/actions/probe-egress", urlencoding(node_hash));
       self.send(reqwest::Method::POST, &path, None).await
   }

   /// POST /api/v1/nodes/{hash}/actions/probe-latency - on-demand latency probe
   /// (Resin v1.2.0 HandleProbeLatency). Requests latency_test_url (default
   /// https://www.gstatic.com/generate_204) through the node, returns
   /// {latency_ewma_ms}. Resin updates the node's TD-EWMA for that domain.
   /// Used by T19-P3 node-pool per-card probe button.
   pub async fn probe_node_latency(&self, node_hash: &str) -> Result<Value> {
       let path = format!("/nodes/{}/actions/probe-latency", urlencoding(node_hash));
       self.send(reqwest::Method::POST, &path, None).await
   }

   /// POST /api/v1/platforms with the full create schema (P21 Milestone B).
    /// Accepts a free-form body (serde_json::Value) so the GUI form can pass
    /// exactly the fields Resin DESIGN.md lists for platform creation:
    ///   name (required), sticky_ttl, regex_filters, region_filters,
    ///   reverse_proxy_miss_action, reverse_proxy_empty_account_behavior,
    ///   reverse_proxy_fixed_account_header, allocation_policy,
    ///   passive_circuit_breaker_disabled.
    /// This is the "create platform with fields" verb: Milestone B uses it to
    /// create auto-{uid} independent platforms when a candidate key is dropped
    /// on the right pane's empty space, with a custom allocation_policy.
    pub async fn create_platform_with_fields(&self, body: Value) -> Result<Value> {
        self.send(reqwest::Method::POST, "/platforms", Some(body))
            .await
    }

    /// GET /api/v1/platforms/{id}/leases — list live leases on a platform (P21).
    /// Resin returns an items-wrapper; the caller parses (account, egress_ip,
    /// node_hash, expiry) to surface the keys already bound to an exit IP on
    /// this platform. This is the "right pane already-active accounts" view.
    pub async fn platform_leases(&self, platform_id: &str) -> Result<Value> {
        let path = format!("/platforms/{}/leases", urlencoding(platform_id));
        self.send_read(&path).await
    }

    // ── Endpoint management (Resin v1.2.0) ───────────────────────────

    /// GET /api/v1/endpoints — list all inbound endpoints (default + custom).
    pub async fn list_endpoints(&self) -> Result<Value> {
        self.send_read("/endpoints").await
    }

    /// POST /api/v1/endpoints — create + immediately start a custom listener.
    pub async fn create_endpoint(&self, body: Value) -> Result<Value> {
        self.send(reqwest::Method::POST, "/endpoints", Some(body)).await
    }

    /// GET /api/v1/endpoints/{endpoint_id} — read a single endpoint.
    pub async fn get_endpoint(&self, endpoint_id: &str) -> Result<Value> {
        let path = format!("/endpoints/{}", urlencoding(endpoint_id));
        self.send_read(&path).await
    }

    /// PATCH /api/v1/endpoints/{endpoint_id} — update port or capabilities (hot-reload).
    pub async fn update_endpoint(&self, endpoint_id: &str, body: Value) -> Result<Value> {
        let path = format!("/endpoints/{}", urlencoding(endpoint_id));
        self.send(reqwest::Method::PATCH, &path, Some(body)).await
    }

    /// DELETE /api/v1/endpoints/{endpoint_id} — delete + close listener.
    pub async fn delete_endpoint(&self, endpoint_id: &str) -> Result<Value> {
        let path = format!("/endpoints/{}", urlencoding(endpoint_id));
        self.send(reqwest::Method::DELETE, &path, None).await
    }

    /// GET /api/v1/system/config — read the system-level configuration
    /// (max_consecutive_failures, cache_flush_interval, probe_timeout, etc.).
    /// T8-1: used by the circuit breaker Settings panel to display current values.
    pub async fn system_config_get(&self) -> Result<Value> {
        self.send(reqwest::Method::GET, "/system/config", None).await
    }

    /// PATCH /api/v1/system/config — update system-level configuration.
    /// T8-1: used to set max_consecutive_failures (circuit breaker threshold).
    pub async fn system_config_patch(&self, body: Value) -> Result<Value> {
        self.send(reqwest::Method::PATCH, "/system/config", Some(body)).await
    }


}

/// Fetch a Clash/ClashMeta subscription URL with a clash-family User-Agent.
///
/// Many subscription providers (the user's test host included) return 403 to a
/// default HTTP client UA but 200 + a full Clash YAML to a clash client UA.
/// We rotate a small pool of clash-family UAs so a single blocked UA string
/// does not make every subscription import fail. 15s timeout: subscription
/// YAML can be large (50+ proxies) on slow hosts.
///
/// Ponytail: no new dependency. reqwest is already a resin-core dep. The UA
/// rotation is a Vec pick, not a pluggable strategy.
pub async fn fetch_clash_subscription(url: &str) -> Result<String> {
    if !url.starts_with("http://") && !url.starts_with("https://") {
        return Err(anyhow!(
            "fetch_clash_subscription: url must start with http(s)://"
        ));
    }
    let http = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(15))
        .redirect(reqwest::redirect::Policy::limited(5))
        .build()
        .context("fetch_clash_subscription: cannot build reqwest::Client")?;
    const UAS: [&str; 4] = [
        "clash-verge/v2.0.0",
        "clash.meta/v1.18.0",
        "ClashforWindows/0.20.39",
        "mihomo/1.18.0",
    ];
    let mut last_err: Option<String> = None;
    for ua in UAS {
        match http.get(url).header("User-Agent", ua).send().await {
            Ok(resp) => {
                let status = resp.status();
                if !status.is_success() {
                    last_err = Some(format!("HTTP {status}"));
                    continue;
                }
                let body = resp
                    .text()
                    .await
                    .context("fetch_clash_subscription: body read failed")?;
                if body.trim().is_empty() {
                    last_err = Some("empty body".to_string());
                    continue;
                }
                return Ok(body);
            }
            Err(e) => {
                last_err = Some(format!("{e:?}"));
                continue;
            }
        }
    }
    Err(anyhow!(
        "fetch_clash_subscription: all UA attempts failed: {}",
        last_err.unwrap_or_else(|| "unknown".to_string())
    ))
}

/// Convert a Clash YAML subscription into a proxies-only block-style YAML.
///
/// Resin's Go YAML parser chokes on flow-style inline mappings
///     - { name: 'X', type: trojan, server: a.com, port: 443 }
/// and on proxy-groups/rules sections that contain unicode group names. Resin
/// only needs the `proxies:` segment for the node pool, so we:
///   1. extract the `proxies:` block (top-level key, until the next
///      same-indent top-level key or EOF),
///   2. rewrite every flow-style `- { k: v, k: v }` list item into
///      block-style with one `k: v` per line,
///   3. drop proxy-groups, rules, dns, rule-providers (irrelevant to egress).
///
/// The parser is a hand-written state machine (~140 lines). We do NOT pull in
/// serde_yaml: the flow-style + unicode edge cases that crash Resin also crash
/// serde_yaml in the same flow-inline mapping form, so a YAML library would
/// not save us here. This is the narrowest tool that fixes the user's test
/// subscription (53 proxies, trojan/vless/hysteria2, unicode names).
pub fn clash_yaml_to_proxies_block(input: &str) -> Result<String> {
    // 1) extract proxies: segment
    let mut start: Option<usize> = None;
    let mut end: Option<usize> = None;
    let lines: Vec<&str> = input.lines().collect();
    for (i, ln) in lines.iter().enumerate() {
        let trimmed = ln.trim_start();
        // top-level key: "proxies:" at the start of the trimmed line, no
        // leading dash, no colon deeper. We accept "proxies:" exactly.
        if trimmed == "proxies:"
            || trimmed.starts_with("proxies:") && !trimmed.starts_with("proxies::")
        {
            // must be column 0 (top-level)
            if ln.chars().take_while(|c| *c == ' ').count() == 0 {
                start = Some(i + 1);
                break;
            }
        }
    }
    let start = start.ok_or_else(|| anyhow!("clash_yaml: no top-level 'proxies:' key"))?;
    // find end: next top-level key (column 0, non-empty, not a comment)
    for (i, ln) in lines.iter().enumerate().skip(start) {
        if ln.is_empty() || ln.trim_start().starts_with('#') {
            continue;
        }
        if ln.chars().take_while(|c| *c == ' ').count() == 0 {
            // top-level line. If it's a key (contains ': ') or a bare key ending ':' -> end.
            if ln.contains(':') {
                end = Some(i);
                break;
            }
        }
    }
    let end = end.unwrap_or(lines.len());
    let proxies_block = &lines[start..end];

    // 2) rewrite each list item from flow-style to block-style.
    let mut out = String::from(
        "proxies:
",
    );
    for ln in proxies_block {
        let s = ln.trim_end();
        if s.trim().is_empty() || s.trim_start().starts_with('#') {
            continue;
        }
        // A list item under proxies is indented and starts with "- ".
        // Flow form: "  - { k: v, k: v, ... }"
        // Block form: "  -" + newline + "      k: v" per field.
        let indent: String = s.chars().take_while(|c| *c == ' ' || *c == '\t').collect();
        let body = s.trim_start();
        if let Some(rest) = body.strip_prefix("- ") {
            let rest = rest.trim();
            if rest.starts_with('{') && rest.ends_with('}') {
                let inner = &rest[1..rest.len() - 1];
                let fields = split_flow_fields(inner);
                out.push_str(&format!(
                    "{indent}-
"
                ));
                for f in fields {
                    let f = f.trim();
                    if f.is_empty() {
                        continue;
                    }
                    out.push_str(&format!(
                        "{indent}    {f}
"
                    ));
                }
            } else {
                // Already block-style or a different shape; keep verbatim.
                out.push_str(&format!(
                    "{s}
"
                ));
            }
        } else {
            // Not a list item (continuation? keep verbatim to be safe).
            out.push_str(&format!(
                "{s}
"
            ));
        }
    }
    if out.lines().count() < 2 {
        return Err(anyhow!(
            "clash_yaml: proxies block is empty after transform"
        ));
    }
    Ok(out)
}

/// Split a flow-style mapping body `k: v, k: v` on commas that are OUTSIDE
/// single quotes. Resin subscriptions use YAML single-quoted scalars
/// (double-quote is rare here). Keys are unquoted identifiers; values may be
/// single-quoted (with '' as an escaped literal single quote), bare numbers,
/// bare strings, or plain words.
fn split_flow_fields(s: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut in_single = false;
    let mut depth: i32 = 0;
    let mut chars = s.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '\'' => {
                in_single = !in_single;
                cur.push(ch);
            }
            '{' | '[' if !in_single => {
                depth += 1;
                cur.push(ch);
            }
            '}' | ']' if !in_single => {
                depth -= 1;
                cur.push(ch);
            }
            ',' if !in_single && depth == 0 => {
                out.push(cur.trim().to_string());
                cur.clear();
            }
            _ => cur.push(ch),
        }
    }
    let last = cur.trim().to_string();
    if !last.is_empty() {
        out.push(last);
    }
    out
}

/// URL-encode a single path segment. serde_urlencoded::encode over-encodes;
/// use a tiny inline encoder for safe chars only (Resin IDs are canonical
/// UUIDs and need no escaping, but we keep the door open for future callers
/// who might pass a name).
fn urlencoding(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c.to_string()
            } else {
                format!("%{:02X}", c as u32)
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_rejects_non_loopback() {
        assert!(ResinClient::new("http://10.0.0.1:2260", "tok".into()).is_err());
        assert!(ResinClient::new("http://example.com:2260", "tok".into()).is_err());
        assert!(ResinClient::new("http://169.254.169.254:2260", "tok".into()).is_err());
    }

    #[test]
    fn new_accepts_loopback_variants() {
        assert!(ResinClient::new("http://127.0.0.1:2260", "tok".into()).is_ok());
        assert!(ResinClient::new("http://localhost:2260", "tok".into()).is_ok());
        assert!(ResinClient::new("http://[::1]:2260", "tok".into()).is_ok());
    }

    #[test]
    fn urlencoding_escapes_disallowed_chars() {
        assert_eq!(urlencoding("foo-bar_b123"), "foo-bar_b123");
        assert_eq!(urlencoding("a/b"), "a%2Fb");
    }

    #[tokio::test]
    async fn mockito_create_platform_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"name":"Platform-A","id":"11111111-1111-1111-1111-111111111111"}"#;
        let m = server
            .mock("POST", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .create_platform_from_name("Platform-A")
            .await
            .expect("create_platform_from_name should succeed against mockito");
        assert_eq!(out["name"], "Platform-A");
        assert_eq!(out["id"], "11111111-1111-1111-1111-111111111111");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_list_platforms_requires_bearer() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"[{"name":"Default","id":"00000000-0000-0000-0000-000000000000"}]"#;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .list_platforms()
            .await
            .expect("list_platforms should succeed");
        assert!(out.is_array());
        assert_eq!(out[0]["name"], "Default");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_delete_platform_204_no_content_round_trip() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("DELETE", "/api/v1/platforms/abc-123")
            .match_header("authorization", "Bearer testtok")
            .with_status(204)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .delete_platform("abc-123")
            .await
            .expect("delete_platform should succeed");
        assert!(out.is_null(), "204 No Content should parse to Value::Null");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn non_2xx_returns_err_with_status_and_excerpt() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms/missing")
            .match_header("authorization", "Bearer testtok")
            .with_status(404)
            .with_body(r#"{"error":"NOT_FOUND","detail":"no such platform"}"#)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c.get_platform("missing").await.unwrap_err().to_string();
        assert!(
            err.contains("404"),
            "error message must surface status: {err}"
        );
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_create_subscription_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"name":"sub-A","id":"22222222-2222-2222-2222-222222222222","source_type":"remote"}"#;
        let m = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .create_subscription(
                serde_json::json!({ "name": "sub-A", "url": "https://example.com/sub" }),
            )
            .await
            .expect("create_subscription should succeed against mockito");
        assert_eq!(out["name"], "sub-A");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_delete_subscription_204_no_content_round_trip() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("DELETE", "/api/v1/subscriptions/abc-123")
            .match_header("authorization", "Bearer testtok")
            .with_status(204)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .delete_subscription("abc-123")
            .await
            .expect("delete_subscription should succeed");
        assert!(out.is_null(), "204 No Content should parse to Value::Null");
        m.assert_async().await;
    }

    #[test]
    fn clash_yaml_to_proxies_block_extracts_proxies_and_converts_flow_style() {
        let yaml = "proxies:\n  - { name: 'alpha', type: trojan, server: a.com, port: 443 }\n  - { name: 'beta', type: vless, server: b.com, port: 80 }\nproxy-groups:\n  - { name: auto, type: select }\nrules:\n  - DOMAIN-SUFFIX,example.com,auto\n";
        let out = clash_yaml_to_proxies_block(yaml).expect("convert should succeed");
        // Should start with proxies: header
        assert!(
            out.starts_with("proxies:\n"),
            "must start with proxies header"
        );
        // proxy-groups / rules must be stripped
        assert!(
            !out.contains("proxy-groups:"),
            "proxy-groups must be stripped"
        );
        assert!(!out.contains("rules:"), "rules must be stripped");
        // Each list item should be block-style: a "-\n" line followed by indented fields
        assert!(out.contains("-\n"), "each item must break into block form");
        assert!(
            out.contains("name: 'alpha'"),
            "alpha name preserved (quoted scalar is fine in block style)"
        );
        assert!(out.contains("name: 'beta'"), "beta name preserved");
        assert!(out.contains("server: a.com"), "alpha server preserved");
        assert!(out.contains("port: 443"), "alpha port preserved");
    }

    #[test]
    fn clash_yaml_to_proxies_block_handles_unicode_names_and_single_quote_escape() {
        // Resin subscriptions often have unicode node names and '' literal quotes.
        let yaml = "proxies:\n  - { name: 'Singapore \u{1F1A8}\u{3014}\u{4E9A}\u{6D32}\u{3015}01', type: trojan, server: sg-1.x.com, port: 443 }\n";
        let out = clash_yaml_to_proxies_block(yaml).expect("convert should succeed with unicode");
        assert!(out.contains("type: trojan"), "type preserved");
        assert!(out.contains("server: sg-1.x.com"), "server preserved");
        assert!(out.contains("port: 443"), "port preserved");
    }

    #[test]
    fn clash_yaml_to_proxies_block_rejects_yaml_without_proxies_key() {
        let yaml = "proxy-groups:\n  - { name: auto, type: select }\n";
        let err = clash_yaml_to_proxies_block(yaml).unwrap_err().to_string();
        assert!(
            err.contains("proxies:"),
            "error should mention missing proxies key: {err}"
        );
    }

    #[test]
    fn split_flow_fields_handles_quoted_comma_inside_value() {
        // A value with an embedded comma inside single quotes must NOT split there.
        let fields = split_flow_fields("name: 'a,b,c', port: 443");
        assert_eq!(fields.len(), 2);
        assert!(
            fields[0].contains("a,b,c"),
            "quoted comma preserved: {fields:?}"
        );
        assert_eq!(fields[1], "port: 443");
    }

    #[tokio::test]
    async fn mockito_update_platform_patches_allocation_policy() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"11111111-1111-1111-1111-111111111111","name":"OpenAI","allocation_policy":"PREFER_LOW_LATENCY"}"#;
        let m = server
            .mock(
                "PATCH",
                "/api/v1/platforms/11111111-1111-1111-1111-111111111111",
            )
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .match_body(mockito::Matcher::PartialJson(
                serde_json::json!({"allocation_policy":"PREFER_LOW_LATENCY"}),
            ))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .update_platform(
                "11111111-1111-1111-1111-111111111111",
                serde_json::json!({"allocation_policy":"PREFER_LOW_LATENCY"}),
            )
            .await
            .expect("update_platform should succeed against mockito");
        assert_eq!(out["allocation_policy"], "PREFER_LOW_LATENCY");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_list_nodes_returns_items_wrapper() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"name":"sg-01","type":"trojan","egress_ip":"1.2.3.4"}],"total":1,"limit":50,"offset":0,"unique_egress_ips":1,"unique_healthy_egress_ips":1}"#;
        let m = server
            .mock("GET", "/api/v1/nodes?limit=500")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .list_nodes()
            .await
            .expect("list_nodes should succeed against mockito");
        assert_eq!(out["total"], 1);
        assert_eq!(out["items"][0]["egress_ip"], "1.2.3.4");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_list_nodes_for_platform_passes_platform_id_query() {
        let mut server = mockito::Server::new_async().await;
        let pid = "22222222-2222-2222-2222-222222222222";
        let body = r#"{"items":[{"node_hash":"a","display_tag":"hk-01","has_outbound":true,"failure_count":0,"region":"hk","tags":[]}],"total":1,"limit":500,"offset":0}"#;
        let m = server
            .mock("GET", mockito::Matcher::Any)
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .list_nodes_for_platform(pid)
            .await
            .expect("list_nodes_for_platform should succeed against mockito");
        assert_eq!(out["total"], 1);
        assert_eq!(out["items"][0]["display_tag"], "hk-01");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_create_platform_with_fields_full_schema() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"44444444-4444-4444-4444-444444444444","name":"auto-ab12cd34","allocation_policy":"BALANCED","routable_node_count":0}"#;
        let m = server
            .mock("POST", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .create_platform_with_fields(serde_json::json!({
                "name": "auto-ab12cd34",
                "allocation_policy": "BALANCED",
                "region_filters": ["hk"],
            }))
            .await
            .expect("create_platform_with_fields should succeed against mockito");
        assert_eq!(out["name"], "auto-ab12cd34");
        assert_eq!(out["allocation_policy"], "BALANCED");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_platform_leases_items_wrapper() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"platform_id":"abc","account":"f00dface","node_hash":"9f2c0b1a6d3e4f5c8a9b0c1d2e3f4a5b","egress_ip":"5.6.7.8","expiry":"2026-02-10T13:00:00Z","last_accessed":"2026-02-10T12:59:50Z"}],"total":1,"limit":50,"offset":0}"#;
        let m = server
            .mock("GET", "/api/v1/platforms/abc/leases")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .platform_leases("abc")
            .await
            .expect("platform_leases should succeed against mockito");
        assert_eq!(out["total"], 1);
        assert_eq!(out["items"][0]["account"], "f00dface");
        assert_eq!(out["items"][0]["egress_ip"], "5.6.7.8");
        m.assert_async().await;
    }


    // ── Endpoint API mockito tests (Resin v1.2.0) ────────────────────

    #[tokio::test]
    async fn mockito_list_endpoints_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"id":"default","port":2260,"allow_management":true,"allow_proxy":true,"source":"environment","read_only":true}]}"#;
        let m = server
            .mock("GET", "/api/v1/endpoints")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c.list_endpoints().await.expect("list_endpoints should succeed");
        assert!(out["items"].is_array());
        assert_eq!(out["items"][0]["id"], "default");
        assert_eq!(out["items"][0]["port"], 2260);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_create_endpoint_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"abc123","port":17990,"allow_management":false,"allow_proxy":true}"#;
        let m = server
            .mock("POST", "/api/v1/endpoints")
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let req = serde_json::json!({"port":17990,"allow_proxy":true,"allow_socks5":true});
        let out = c.create_endpoint(req).await.expect("create_endpoint should succeed");
        assert_eq!(out["id"], "abc123");
        assert_eq!(out["port"], 17990);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_update_endpoint_patch() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"abc123","port":17991,"allow_proxy":true}"#;
        let m = server
            .mock("PATCH", "/api/v1/endpoints/abc123")
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let req = serde_json::json!({"port":17991});
        let out = c.update_endpoint("abc123", req).await.expect("update_endpoint should succeed");
        assert_eq!(out["port"], 17991);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_delete_endpoint_204() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("DELETE", "/api/v1/endpoints/abc123")
            .match_header("authorization", "Bearer testtok")
            .with_status(204)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c.delete_endpoint("abc123").await.expect("delete_endpoint should succeed");
        // 204 no content -> empty Value
        assert!(out.is_null() || out.is_object());
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_get_endpoint_single() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"default","port":2260,"allow_socks5":true,"source":"environment","read_only":true}"#;
        let m = server
            .mock("GET", "/api/v1/endpoints/default")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c.get_endpoint("default").await.expect("get_endpoint should succeed");
        assert_eq!(out["id"], "default");
        assert_eq!(out["port"], 2260);
        assert_eq!(out["source"], "environment");
        assert_eq!(out["read_only"], true);
        m.assert_async().await;
    }


    #[tokio::test]
    async fn mockito_read_retry_503_then_200() {
        // First call returns 503, second returns 200 (send_read retries up to 2 times)
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"name":"retry-test"}],"total":1}"#;
        let m503 = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(503)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"transient"}"#)
            .expect(1)
            .create_async()
            .await;
        let m200 = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c.list_platforms().await.expect("list_platforms should succeed after retry");
        assert_eq!(out["items"][0]["name"], "retry-test");
        // First attempt (503) + second attempt (200) = 2 hits total
        m503.assert_async().await;
        m200.assert_async().await;


    }

    #[tokio::test]
    async fn mockito_read_retry_all_503_exhausts() {
        // All 3 attempts return 503 -> error is surfaced
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(503)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"transient"}"#)
            .expect(3)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let result = c.list_platforms().await;
        assert!(result.is_err(), "should error after exhausting retries");
        // 1 initial + 2 retries = 3 total attempts
        m.assert_async().await;

    }

    #[tokio::test]
    async fn mockito_read_no_retry_on_4xx() {
        // 404 should NOT retry (4xx is not transient)
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(404)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"not found"}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
       let result = c.list_platforms().await;
       assert!(result.is_err(), "404 should error without retry");
       // Should be called exactly once (no retry on 4xx)
       m.assert_async().await;

   }

   #[tokio::test]
   async fn mockito_refresh_subscription_content_patches_local_content() {
       // T19-P2: PATCH /subscriptions/{id} with {content} body -> 200 updated object.
       let mut server = mockito::Server::new_async().await;
       let m = server
           .mock("PATCH", "/api/v1/subscriptions/sub-uuid-1")
           .match_header("authorization", "Bearer testtok")
           .match_body(r#"{"content":"proxies:\n  - {name: n1}"}"#)
           .with_status(200)
           .with_header("content-type", "application/json")
           .with_body(r#"{"id":"sub-uuid-1","name":"main","source_type":"local","node_count":1}"#)
           .expect(1)
           .create_async()
           .await;
       let base = server.url();
       let c = ResinClient::new(&base, "testtok".into()).unwrap();
       let out = c
           .refresh_subscription_content("sub-uuid-1", "proxies:\n  - {name: n1}".to_string())
           .await
           .expect("refresh_subscription_content should succeed");
       assert_eq!(out["id"], "sub-uuid-1");
       assert_eq!(out["node_count"], 1);
       m.assert_async().await;
   }

   #[tokio::test]
   async fn mockito_probe_node_egress_returns_egress_ip_region_latency() {
       // T19-P3: POST /nodes/{hash}/actions/probe-egress -> {egress_ip, region, latency_ewma_ms}.
       let mut server = mockito::Server::new_async().await;
       let m = server
           .mock("POST", "/api/v1/nodes/abc123/actions/probe-egress")
           .match_header("authorization", "Bearer testtok")
           .with_status(200)
           .with_header("content-type", "application/json")
           .with_body(r#"{"egress_ip":"203.0.113.1","region":"us","latency_ewma_ms":123.45}"#)
           .expect(1)
           .create_async()
           .await;
       let base = server.url();
       let c = ResinClient::new(&base, "testtok".into()).unwrap();
       let out = c
           .probe_node_egress("abc123")
           .await
           .expect("probe_node_egress should succeed");
       assert_eq!(out["egress_ip"], "203.0.113.1");
       assert_eq!(out["region"], "us");
       assert_eq!(out["latency_ewma_ms"], 123.45);
       m.assert_async().await;
   }

   #[tokio::test]
   async fn mockito_probe_node_latency_returns_latency_ewma_ms() {
       // T19-P3: POST /nodes/{hash}/actions/probe-latency -> {latency_ewma_ms}.
       let mut server = mockito::Server::new_async().await;
       let m = server
           .mock("POST", "/api/v1/nodes/abc123/actions/probe-latency")
           .match_header("authorization", "Bearer testtok")
           .with_status(200)
           .with_header("content-type", "application/json")
           .with_body(r#"{"latency_ewma_ms":89.12}"#)
           .expect(1)
           .create_async()
           .await;
       let base = server.url();
       let c = ResinClient::new(&base, "testtok".into()).unwrap();
       let out = c
           .probe_node_latency("abc123")
           .await
           .expect("probe_node_latency should succeed");
       assert_eq!(out["latency_ewma_ms"], 89.12);
       m.assert_async().await;
   }

   #[test]
   fn t15_4_shared_client_returns_same_instance() {
        // Two calls to shared_client() must return pointers to the same Client.
        let a = shared_client();
        let b = shared_client();
        // Pointer equality: same address = same Client
        assert!(std::ptr::eq(a, b), "shared_client() returned different Client instances");
    }
}
