//! Thin async wrapper around the Resin sidecar control-plane REST API.
//!
//! Path A uses the Resin Go binary as the production proxy runtime and lets it
//! own the SQLite state (platforms / accounts / leases / subscriptions).
//! This client is the Rust-side forwarder the IPC commands layer uses to
//! talk to the sidecar admin REST API. It is constructed from a (api_base,
//! admin_token) pair captured in the Tauri shell from
//! `src-tauri/src/sidecar.rs::SidecarHandle` and never exposes the token to
//! the webview (AGENTS 7.6).
//!
//! This is a small reqwest wrapper, not an SDK. We do NOT model
//! every Resin REST endpoint. We expose only the verbs the IPC commands
//! layer currently needs:
//!   - POST /api/v1/platforms               create_platform
//!   - GET  /api/v1/platforms               list_platforms
//!   - GET  /api/v1/platforms/{id}           get_platform
//!   - DELETE /api/v1/platforms/{id}         delete_platform
//!   - GET  /api/v1/metrics/realtime/leases active_leases
//! Any request body is accepted as serde_json::Value so the caller can pass
//! exactly what the React form produced. We provide one canonical helper
//! (create_platform_from_name) for the common single-name path.
//!
//! Resin design notes:
//!   - Admin API token goes in `Authorization: Bearer <admin_token>`.
//!   - /healthz is the only unauthenticated endpoint (the safety-net uses it).
//!   - All admin endpoints are under /api/v1/*.
//!   - Path parameters ({id}) are URL-encoded: the spec validates platform_id
//!     as a canonical UUID so encoding is a no-op in practice, but we encode
//!     defensively in case a caller passes a non-canonical form.

use std::sync::OnceLock;
use anyhow::{anyhow, Context, Result};
use serde_json::Value;
use url::Url;
use crate::ipc_error::IpcError;

/// Loopback-only connection to the Resin sidecar admin REST API.
///
/// The `base` URL MUST always resolve to 127.0.0.1 (it is constructed from
/// SidecarHandle::api_base() which is always http://127.0.0.1:<port>). The
/// admin_token is the per-session secret generated by boot_resin; it NEVER
/// crosses the IPC boundary into the webview.
#[derive(Clone)]
pub struct ResinClient {
    base: Url,
    admin_token: String,
    http: reqwest::Client,
}

const API_PREFIX: &str = "/api/v1";

/// Shared reqwest::Client reused across all ResinClient instances.
/// The IPC layer constructs a fresh ResinClient per call (one per Tauri
/// command), but reqwest::Client owns a connection pool + TLS context.
/// Reusing a single Client avoids building a new pool per IPC call.
/// std::sync::OnceLock (Rust stdlib, zero new deps).
static SHARED_CLIENT: OnceLock<reqwest::Client> = OnceLock::new();

fn shared_client() -> &'static reqwest::Client {
    SHARED_CLIENT.get_or_init(|| {
        reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(8))
            .build()
            .expect("resin_client: cannot build shared reqwest::Client")
    })
}

impl ResinClient {
    /// Construct a new client from a 127.0.0.1 base URL + admin token.
    /// We reject non-loopback bases defensively even though the only caller
    /// (boot_resin) already guarantees a loopback base.
    pub fn new(base: &str, admin_token: String) -> Result<Self> {
        let url = Url::parse(base).context("resin_client: invalid base URL")?;
        let host = url.host_str().unwrap_or("");
        let loopback = matches!(host, "127.0.0.1" | "localhost" | "::1" | "[::1]");
        if !loopback {
            return Err(anyhow!(
                "resin_client: base host '{host}' is not loopback; rejected (SSRF guard)"
            ));
        }
        // reuse the shared reqwest::Client (connection pool + TLS).
        let http = shared_client().clone();
        Ok(Self {
            base: url,
            admin_token,
            http,
        })
    }

    /// Return a copy of the admin token for the safety-net poller (which for
    /// /healthz does not need it, but keeps consumers honest about scope).
    pub fn admin_token(&self) -> &str {
        &self.admin_token
    }

    /// Compose an absolute URL on the /api/v1 prefix.
    fn url(&self, path: &str) -> Result<Url> {
        let trimmed = path.trim_start_matches('/');
        let full = format!("{API_PREFIX}/{trimmed}");
        self.base.join(&full).context("resin_client: join failed")
    }

    /// Send an authenticated admin request and return the parsed JSON body.
    /// For non-success (2xx) responses we surface the upstream status + a
    /// short body excerpt rather than swallowing the error.
/// (ADR-0018): Read-only auto-retry wrapper. Calls send() and
    /// retries up to READ_MAX_RETRIES times with READ_RETRY_DELAY_MS between
    /// attempts. Only for GET methods (read-only); write methods use send()
    /// directly. Retries on network error or 5xx (server transient failure);
    /// does NOT retry on 4xx (client error) or success.
    async fn send_read(
        &self,
        path: &str,
    ) -> Result<Value> {
        let max_retries = 2u32;
        let delay = std::time::Duration::from_millis(500);
        let mut last_err = None;
        for attempt in 0..=max_retries {
            match self.send(reqwest::Method::GET, path, None).await {
                Ok(v) => return Ok(v),
                Err(e) => {
                    // Retry on network errors or 5xx; don't retry 4xx or parse
                    // errors (classifier shared with send_with_retry)
                    if attempt < max_retries && Self::is_transient_5xx(&e) {
                        tracing::warn!(
                            "resin_client: read retry {}/{} for {path} after: {}",
                            attempt + 1, max_retries, e
                        );
                        last_err = Some(e);
                        tokio::time::sleep(delay).await;
                        continue;
                    }
                    return Err(e);
                }
            }
        }
        Err(last_err.unwrap_or_else(|| anyhow!("resin_client: exhausted read retries for {path}")))
    }

/// transient-failure classifier shared by send_read and the
    /// write-retry wrapper below. Matches network errors and the 500/502/503/504
    /// band rendered by send()'s error string; 4xx and parse errors never
    /// retry (a rejected body is not transient).
    fn is_transient_5xx(err: &anyhow::Error) -> bool {
        let s = format!("{err}");
        s.contains("request send failed")
            || s.contains("-> 503")
            || s.contains("-> 502")
            || s.contains("-> 500")
            || s.contains("-> 504")
    }

/// generic 5xx retry wrapper over send() for write verbs
    /// (POST/PATCH/PUT/DELETE). Same rule as send_read: 2 retries, 500ms
    /// then 1000ms, no retry on 4xx, parse errors, or success. A retried
    /// POST that actually landed (response lost) can re-apply on Resin; the
    /// create paths here are name-keyed (duplicate POST returns the existing
    /// row or a 4xx, never a second copy) and the action paths converge
    /// idempotently, which keeps the retry honest. Each retry logs at warn
    /// level with the failure reason so a flapping Resin stays visible.
    async fn send_with_retry(
        &self,
        method: reqwest::Method,
        path: &str,
        body: Option<Value>,
    ) -> Result<Value> {
        let max_retries = 2u32;
        let mut last_err = None;
        for attempt in 0..=max_retries {
            match self.send(method.clone(), path, body.clone()).await {
                Ok(v) => return Ok(v),
                Err(e) => {
                    if attempt < max_retries && Self::is_transient_5xx(&e) {
                        tracing::warn!(
                            "resin_client: write retry {}/{} for {} {path} after: {}",
                            attempt + 1, max_retries, method, e
                        );
                        last_err = Some(e);
                        tokio::time::sleep(std::time::Duration::from_millis(if attempt == 0 { 500 } else { 1000 })).await;
                        continue;
                    }
                    return Err(e);
                }
            }
        }
        Err(last_err.unwrap_or_else(|| {
            anyhow!("resin_client: exhausted write retries for {} {path}", method)
        }))
    }

    async fn send(

        &self,
        method: reqwest::Method,
        path: &str,
        body: Option<Value>,
    ) -> Result<Value> {
        let url = self.url(path)?;
        let method_str = method.as_str().to_owned();
        let mut req = self
            .http
            .request(method, url)
            .header("Authorization", format!("Bearer {}", self.admin_token))
            .header("Accept", "application/json");
        if let Some(b) = body {
            req = req.header("Content-Type", "application/json").json(&b);
        }
        let resp = req
            .send()
            .await
            .context("resin_client: request send failed")?;
        let status = resp.status();
        if !status.is_success() {
            let txt = resp.text().await.unwrap_or_default();
            let excerpt = if txt.len() > 256 {
                format!("{}...", &txt[..256])
            } else {
                txt.clone()
            };
            return Err(anyhow!(
                "resin_client: {method_str} {path} -> {status}: {excerpt}"
            ));
        }
        if status == reqwest::StatusCode::NO_CONTENT {
            return Ok(Value::Null);
        }
        let ct = resp
            .headers()
            .get(reqwest::header::CONTENT_TYPE)
            .and_then(|v| v.to_str().ok())
            .unwrap_or("")
            .to_string();
        if ct.contains("application/json") {
            let v = resp
                .json::<Value>()
                .await
                .context("resin_client: json decode failed")?;
            Ok(v)
        } else {
            let txt = resp.text().await.unwrap_or_default();
            Ok(Value::String(txt))
        }
    }

    /// POST /api/v1/platforms
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R08
    /// body: free-form serde_json::Value (Resin accepts the fields described in
    /// DESIGN.md platform POST section); only `name` is required by Resin.
    pub async fn create_platform(&self, body: Value) -> Result<Value> {
        self.send_with_retry(reqwest::Method::POST, "/platforms", Some(body))
            .await
    }

    /// Convenience: create a platform with just a name. Sticky TTL, filters,
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R08
    /// allocation policy left at Resin defaults.
    pub async fn create_platform_from_name(&self, name: &str) -> Result<Value> {
        // The Resin V1 name rule lives in `validate_platform_name` so the headless
        // BFF enforces the identical bound on POST /api/v1/platforms (
        // A-006: one validation, effective in both places).
        validate_platform_name(name).map_err(|e| anyhow!("resin_client: {e}"))?;
        self.create_platform(serde_json::json!({ "name": name }))
            .await
    }

    /// GET /api/v1/platforms
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R07
    pub async fn list_platforms(&self) -> Result<Value> {
        self.send_read("/platforms").await
    }

    /// GET /api/v1/platforms/{id}
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R10
    pub async fn get_platform(&self, id: &str) -> Result<Value> {
        let path = format!("/platforms/{}", urlencoding(id));
        self.send_read(&path).await
    }

    /// DELETE /api/v1/platforms/{id}
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R12
    pub async fn delete_platform(&self, id: &str) -> Result<Value> {
        let path = format!("/platforms/{}", urlencoding(id));
        self.send_with_retry(reqwest::Method::DELETE, &path, None).await
    }

    /// GET /api/v1/metrics/realtime/leases — active-lease snapshot used by the
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R49
    /// desktop Topology view in place of the dead resin-core LeaseTable.
    pub async fn active_leases(&self) -> Result<Value> {
        self.send_read("/metrics/realtime/leases")
            .await
    }

    /// GET /api/v1/metrics/snapshots/node-pool — global node pool snapshot.
    pub async fn node_pool_snapshot(&self) -> Result<Value> {
        self.send_read("/metrics/snapshots/node-pool")
            .await
    }

    /// POST /subscriptions - create a subscription. `source_type` is "remote"
    /// (with a `url`) or "local" (with `content`). The webview supplies the
    /// fields via a free-form JSON body; Resin fetches the nodes itself.
    pub async fn create_subscription(&self, body: Value) -> Result<Value> {
        self.send_with_retry(reqwest::Method::POST, "/subscriptions", Some(body))
            .await
    }

    /// GET /subscriptions - list all subscriptions (raw array).
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R25
    pub async fn list_subscriptions(&self) -> Result<Value> {
        self.send_read("/subscriptions")
            .await
    }

   /// DELETE /subscriptions/{id} - remove a subscription (204 -> Null).
   /// @see docs/architecture/RESIN_API_COVERAGE.md #R29
   pub async fn delete_subscription(&self, id: &str) -> Result<Value> {
       let path = format!("/subscriptions/{}", urlencoding(id));
       self.send_with_retry(reqwest::Method::DELETE, &path, None).await
   }

    /// POST /api/v1/subscriptions/{id}/actions/refresh - trigger Resin-native
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R30
    /// remote subscription refresh. Resin's Scheduler re-pulls the remote URL
    /// via its own clash.meta UA fetcher (cmd/resin/main.go const downloadUserAgent).
    /// The shell no longer re-fetches or converts the Clash YAML itself
    /// (the former fetch_clash_subscription+clash_yaml_to_proxies_block+PATCH
    /// chain is deleted; ADR-0045 supersedes ADR-0044 S2 for the refresh path).
    /// Refresh on a local-source subscription is a no-op re-parse of in-memory
    /// content, so the paired subscription_add migrated to source_type="remote".
    /// No request body is sent; Resin kicks its scheduler tick synchronously.
    pub async fn refresh_subscription_native(&self, id: &str) -> Result<Value> {
        let path = format!("/subscriptions/{}/actions/refresh", urlencoding(id));
        self.send_with_retry(reqwest::Method::POST, &path, None).await
    }


   /// PATCH /api/v1/platforms/{id} - update platform fields (allocation_policy,
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R11
   /// regex_filters, region_filters, sticky_ttl, etc). Resin validates the
   /// body and returns 400 with a descriptive error for invalid enum values.
    /// Used by the topology canvas hot-switch (Phase R1/R2).
    pub async fn update_platform(&self, id: &str, body: Value) -> Result<Value> {
        let path = format!("/platforms/{}", urlencoding(id));
        self.send_with_retry(reqwest::Method::PATCH, &path, Some(body)).await
    }

    /// GET /api/v1/nodes - list all proxy nodes (the "C category" ip channels).
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R36
    /// Resin paginates this endpoint (default limit < total); without an
    /// explicit limit the frontend gets a stale partial view while the node-pool
    /// snapshot grows. We pass an explicit limit (and optional offset) so the
    /// per-node table reflects the same count as the stats card.
    pub async fn list_nodes(&self) -> Result<Value> {
        self.send_read("/nodes?limit=500")
            .await
    }

   /// GET /api/v1/nodes?platform_id=<id>&limit=500 - the routable node list
   /// @see docs/architecture/RESIN_API_COVERAGE.md #R36
   /// for a single platform (Resin DESIGN.md "list nodes" with platform_id filter).
   pub async fn list_nodes_for_platform(&self, platform_id: &str) -> Result<Value> {
       let path = format!("/nodes?limit=500&platform_id={}", platform_id);
       self.send_read(&path).await
   }

   /// POST /api/v1/nodes/{hash}/actions/probe-egress - on-demand egress probe
   /// @see docs/architecture/RESIN_API_COVERAGE.md #R38
   /// (Resin v1.2.0 HandleProbeEgress). Requests cloudflare.com/cdn-cgi/trace
   /// through the node, returns {egress_ip, region, latency_ewma_ms}. Resin
   /// updates the node's egress_ip + TD-EWMA + routing as a side effect.
   /// Used by node-pool per-card probe button.
   pub async fn probe_node_egress(&self, node_hash: &str) -> Result<Value> {
       let path = format!("/nodes/{}/actions/probe-egress", urlencoding(node_hash));
       self.send_with_retry(reqwest::Method::POST, &path, None).await
   }

   /// POST /api/v1/nodes/{hash}/actions/probe-latency - on-demand latency probe
   /// @see docs/architecture/RESIN_API_COVERAGE.md #R39
   /// (Resin v1.2.0 HandleProbeLatency). Requests latency_test_url (default
   /// https://www.gstatic.com/generate_204) through the node, returns
   /// {latency_ewma_ms}. Resin updates the node's TD-EWMA for that domain.
   /// Used by node-pool per-card probe button.
   pub async fn probe_node_latency(&self, node_hash: &str) -> Result<Value> {
       let path = format!("/nodes/{}/actions/probe-latency", urlencoding(node_hash));
       self.send_with_retry(reqwest::Method::POST, &path, None).await
   }

   /// POST /api/v1/platforms with the full create schema.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R08
    /// Accepts a free-form body (serde_json::Value) so the GUI form can pass
    /// exactly the fields Resin DESIGN.md lists for platform creation:
    ///   name (required), sticky_ttl, regex_filters, region_filters,
    ///   reverse_proxy_miss_action, reverse_proxy_empty_account_behavior,
    ///   reverse_proxy_fixed_account_header, allocation_policy,
    ///   passive_circuit_breaker_disabled.
    /// This is the "create platform with fields" verb: Milestone B uses it to
    /// create auto-{uid} independent platforms when a candidate key is dropped
    /// on the right pane's empty space, with a custom allocation_policy.
    pub async fn create_platform_with_fields(&self, body: Value) -> Result<Value> {
        self.send_with_retry(reqwest::Method::POST, "/platforms", Some(body))
            .await
    }

    /// GET /api/v1/platforms/{id}/leases — list live leases on a platform.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R20
    /// Resin returns an items-wrapper; the caller parses (account, egress_ip,
    /// node_hash, expiry) to surface the keys already bound to an exit IP on
    /// this platform. This is the "right pane already-active accounts" view.
    pub async fn platform_leases(&self, platform_id: &str) -> Result<Value> {
        let path = format!("/platforms/{}/leases", urlencoding(platform_id));
        self.send_read(&path).await
    }

    // ── Endpoint management (Resin v1.2.0) ───────────────────────────

    /// GET /api/v1/endpoints — list all inbound endpoints (default + custom).
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R15
    pub async fn list_endpoints(&self) -> Result<Value> {
        self.send_read("/endpoints").await
    }

    /// POST /api/v1/endpoints — create + immediately start a custom listener.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R16
    pub async fn create_endpoint(&self, body: Value) -> Result<Value> {
        self.send_with_retry(reqwest::Method::POST, "/endpoints", Some(body)).await
    }

    /// GET /api/v1/endpoints/{endpoint_id} — read a single endpoint.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R17
    pub async fn get_endpoint(&self, endpoint_id: &str) -> Result<Value> {
        let path = format!("/endpoints/{}", urlencoding(endpoint_id));
        self.send_read(&path).await
    }

    /// PATCH /api/v1/endpoints/{endpoint_id} — update port or capabilities (hot-reload).
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R18
    pub async fn update_endpoint(&self, endpoint_id: &str, body: Value) -> Result<Value> {
        let path = format!("/endpoints/{}", urlencoding(endpoint_id));
        self.send_with_retry(reqwest::Method::PATCH, &path, Some(body)).await
    }

    /// DELETE /api/v1/endpoints/{endpoint_id} — delete + close listener.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R19
    pub async fn delete_endpoint(&self, endpoint_id: &str) -> Result<Value> {
        let path = format!("/endpoints/{}", urlencoding(endpoint_id));
        self.send_with_retry(reqwest::Method::DELETE, &path, None).await
    }

    /// GET /api/v1/system/config — read the system-level configuration
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R03
    /// (max_consecutive_failures, cache_flush_interval, probe_timeout, etc.).
    /// used by the circuit breaker Settings panel to display current values.
    pub async fn system_config_get(&self) -> Result<Value> {
        self.send(reqwest::Method::GET, "/system/config", None).await
    }

    /// PATCH /api/v1/system/config — update system-level configuration.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R06
    /// used to set max_consecutive_failures (circuit breaker threshold).
    pub async fn system_config_patch(&self, body: Value) -> Result<Value> {
        self.send_with_retry(reqwest::Method::PATCH, "/system/config", Some(body)).await
    }

    // ── Request logs (REST seam, replaces direct request_logs*.db read) ──

    /// GET /api/v1/request-logs?limit=N — tail of the Resin request log
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R44
    /// ( ADR-0005 Q6 said probe the endpoint
    /// before coding: the endpoint was verified in the bundled sidecar
    /// (docs/RESIN_UPSTREAM_MANIFEST.yaml v1.2.0): the embedded WebUI calls
    /// GET /api/v1/request-logs with from/to/platform_name/account/target_host/
    /// egress_ip/proxy_type/net_ok/http_status/limit/cursor params, rows carry
    /// ts_ns/platform_name/account/target_host/egress_ip/proxy_type/net_ok/
    /// http_method/http_status/duration_ns/resin_error, ORDER BY ts_ns DESC.
    /// Query params beyond limit are appended only when Some.
    /// Fuzzy name filters (platform_name/account/target_host/egress_ip) are
    /// URL-encoded here; Resin matches them fuzzily server-side.
    pub async fn request_logs(
        &self,
        limit: u32,
        query: Option<&RequestLogQuery>,
    ) -> Result<Value> {
        let mut path = format!("/request-logs?limit={}", limit);
        if let Some(q) = query {
            if let Some(v) = q.platform_name.as_deref() {
                path.push_str(&format!("&platform_name={}", urlencoding(v)));
            }
            if let Some(v) = q.account.as_deref() {
                path.push_str(&format!("&account={}", urlencoding(v)));
            }
            if let Some(v) = q.target_host.as_deref() {
                path.push_str(&format!("&target_host={}", urlencoding(v)));
            }
            if let Some(v) = q.egress_ip.as_deref() {
                path.push_str(&format!("&egress_ip={}", urlencoding(v)));
            }
            if let Some(v) = q.proxy_type.as_deref() {
                path.push_str(&format!("&proxy_type={}", urlencoding(v)));
            }
            if let Some(v) = q.net_ok.as_deref() {
                path.push_str(&format!("&net_ok={}", urlencoding(v)));
            }
            if let Some(v) = q.http_status.as_deref() {
                path.push_str(&format!("&http_status={}", urlencoding(v)));
            }
            if let Some(v) = q.cursor.as_deref() {
                path.push_str(&format!("&cursor={}", urlencoding(v)));
            }
        }
        self.send_read(&path).await
    }

    /// GET /api/v1/request-logs/{log_id} — single request log entry.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R45
    pub async fn get_request_log(&self, log_id: &str) -> Result<Value> {
        let path = format!("/request-logs/{}", urlencoding(log_id));
        self.send_read(&path).await
    }

    /// GET /api/v1/request-logs/{log_id}/payloads — captured request/response
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R46
    /// bodies for a log entry (only present when payload logging is enabled).
    pub async fn get_request_log_payloads(&self, log_id: &str) -> Result<Value> {
        let path = format!("/request-logs/{}/payloads", urlencoding(log_id));
        self.send_read(&path).await
    }

    // ── Account header rules (coexistence with process_route per ADR-0063) ──

    /// GET /api/v1/account-header-rules?limit=1000&offset=0 — list all rules.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R32
    /// Page size mirrors the bundled WebUI rules client (limit=1000) so the
    /// full rule set comes back in one page (Resin's default page limit is
    /// 50). `keyword` filters server-side over url_prefix + header values
    /// when non-empty; the {"items":[...],"total","limit","offset"} wrapper
    /// is passed through verbatim.
    pub async fn list_account_header_rules(&self, keyword: Option<&str>) -> Result<Value> {
        let mut path = String::from("/account-header-rules?limit=1000&offset=0");
        if let Some(k) = keyword {
            let k = k.trim();
            if !k.is_empty() {
                path.push_str("&keyword=");
                path.push_str(&urlencoding(k));
            }
        }
        self.send_read(&path).await
    }

    /// PUT /api/v1/account-header-rules/{url_prefix...} — upsert one rule.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R33
    /// The url_prefix lives in the PATH (encoded with encodeURIComponent
    /// semantics — see encode_uri_component); the body carries ONLY
    /// {"headers":[...]} because Resin rejects a url_prefix field in the
    /// body (handler_rules.go:75-78). 201 = created, 200 = updated. Header
    /// names are validated by Resin as RFC 7230 tokens; length/control-char
    /// caps here are the §7.5-style defensive mirror.
    pub async fn put_account_header_rules(&self, url_prefix: &str, headers: &[String]) -> Result<Value> {
        if url_prefix.trim().is_empty() {
            return Err(anyhow!("resin_client: url_prefix cannot be empty"));
        }
        if url_prefix.len() > 253 {
            return Err(anyhow!("resin_client: url_prefix length > 253"));
        }
        if url_prefix.bytes().any(|b| b == 0 || b < 0x20 || b == 0x7f) {
            return Err(anyhow!("resin_client: url_prefix contains control characters"));
        }
        let path = format!("/account-header-rules/{}", encode_uri_component(url_prefix));
        let body = serde_json::json!({ "headers": headers });
        self.send_with_retry(reqwest::Method::PUT, &path, Some(body)).await
    }

    /// POST /api/v1/account-header-rules:resolve — matcher debug aid.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R34
    /// Body is {"url": <absolute http(s) url>}; the response is
    /// {"matched_url_prefix": ..., "headers": [...]} — empty fields mean NO
    /// rule matched, which is a 200 result and not an error.
    pub async fn resolve_account_header_rule(&self, url: &str) -> Result<Value> {
        if url.trim().is_empty() {
            return Err(anyhow!("resin_client: url cannot be empty"));
        }
        if url.len() > 2048 {
            return Err(anyhow!("resin_client: url length > 2048"));
        }
        if url.bytes().any(|b| b == 0 || b < 0x20 || b == 0x7f) {
            return Err(anyhow!("resin_client: url contains control characters"));
        }
        let body = serde_json::json!({ "url": url });
        self.send_with_retry(reqwest::Method::POST, "/account-header-rules:resolve", Some(body)).await
    }

    /// DELETE /api/v1/account-header-rules/{url_prefix...} — remove one rule.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R35
    /// Keyed by the normalized url_prefix (NOT an id); 204 -> Ok(Null). The
    /// fallback rule "*" is rejected upstream with invalid_argument and
    /// surfaces here as a 400 error string.
    pub async fn delete_account_header_rule(&self, url_prefix: &str) -> Result<Value> {
        if url_prefix.trim().is_empty() {
            return Err(anyhow!("resin_client: url_prefix cannot be empty"));
        }
        if url_prefix.len() > 253 {
            return Err(anyhow!("resin_client: url_prefix length > 253"));
        }
        if url_prefix.bytes().any(|b| b == 0 || b < 0x20 || b == 0x7f) {
            return Err(anyhow!("resin_client: url_prefix contains control characters"));
        }
        let path = format!("/account-header-rules/{}", encode_uri_component(url_prefix));
        self.send_with_retry(reqwest::Method::DELETE, &path, None).await
    }

    /// GET /api/v1/metrics/realtime/throughput — realtime ingress/egress
    /// throughput ring samples. minimal set (ADR-0064): the shell sends
    /// no from/to params, so Resin's parseMetricsTimeRange applies its own
    /// defaults (to=now, from=to-1h). Response shape (handler_metrics.go:147):
    /// {"step_seconds": N, "items": [{"ts","ingress_bps","egress_bps"}]}.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R47
    pub async fn realtime_throughput(&self) -> Result<Value> {
        self.send_read("/metrics/realtime/throughput").await
    }

    /// GET /api/v1/metrics/history/probes?from=<RFC3339>&to=<RFC3339> —
    /// probe-count history buckets from Resin's metrics.db. minimal set
    /// (ADR-0064). `from`/`to` are RFC3339Nano strings (handler_metrics.go:15):
    /// Resin rejects anything else with 400 INVALID_ARGUMENT, so the IPC layer
    /// boundary-validates and converts before calling this. None passes no
    /// param at all — Resin then applies its own defaults (to=now,
    /// from=to-1h), so the shell never re-derives time semantics. Response:
    /// {"bucket_seconds": N, "items": [{"bucket_start","bucket_end","total_count"}]}.
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R53
    pub async fn probe_history(&self, from: Option<&str>, to: Option<&str>) -> Result<Value> {
        let mut path = "/metrics/history/probes".to_string();
        let mut sep = '?';
        if let Some(f) = from {
            path.push(sep);
            sep = '&';
            path.push_str(&format!("from={}", urlencoding(f)));
        }
        if let Some(t) = to {
            path.push(sep);
            path.push_str(&format!("to={}", urlencoding(t)));
        }
        self.send_read(&path).await
    }

    /// Resolve a platform name to its Resin UUID.
    ///
    /// Resin's endpoint design is hybrid: list endpoints are name-keyed
    /// (`GET /platforms` rows carry `name`+`id`) while single-resource
    /// endpoints are UUID-keyed (`DELETE /platforms/{id}`, `GET
    /// /platforms/{id}/leases`). Every name-knowing caller previously
    /// re-implemented the "list all -> match name -> take id" two-step hop;
    /// this helper (plus the pure `resolve_id_in`) is the one canonical
    /// implementation. Miss resolves to `IpcError::NotFound` — NOT a panic
    /// and not a stringly error (F3/§7.5).
    ///
    /// The list GET failure is mapped through `map_resin_error` so upstream
    /// errors keep their typed face (`ResinUpstream` for a 5xx, etc.) exactly
    /// as the former inline command bodies produced.
    ///
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R07
    pub async fn resolve_platform_id_by_name(&self, name: &str) -> Result<String, IpcError> {
        validate_resolve_name(name, "platform")?;
        let list = self
            .list_platforms()
            .await
            .map_err(|e| crate::ipc_error::map_resin_error(&e.to_string()))?;
        resolve_id_in(&list, name)
            .ok_or_else(|| IpcError::not_found(&format!("platform not found: {name}")))
    }

    /// Resolve a subscription name to its Resin UUID.
    /// Same hybrid-shape motivation and error contract as
    /// `resolve_platform_id_by_name`, over `GET /subscriptions`.
    ///
    /// @see docs/architecture/RESIN_API_COVERAGE.md #R25
    pub async fn resolve_subscription_id_by_name(&self, name: &str) -> Result<String, IpcError> {
        validate_resolve_name(name, "subscription")?;
        let list = self
            .list_subscriptions()
            .await
            .map_err(|e| crate::ipc_error::map_resin_error(&e.to_string()))?;
        resolve_id_in(&list, name)
            .ok_or_else(|| IpcError::not_found(&format!("subscription not found: {name}")))
    }
}

/// §7.5 boundary validation for name→UUID resolution (F3): the
/// name is a DNS-host-scale identifier, so cap it at 253 chars and reject
/// NUL/control characters. Returns `IpcError::InvalidInput` — never panics,
/// mirroring the per-endpoint guards above (create_platform_from_name etc.).
fn validate_resolve_name(name: &str, field: &str) -> Result<(), IpcError> {
    if name.is_empty() || name.len() > 253 {
        return Err(IpcError::invalid_input(&format!(
            "{field} name length out of range (1..=253)"
        )));
    }
    if name.bytes().any(|b| b == 0 || b < 0x20 || b == 0x7f) {
        return Err(IpcError::invalid_input(&format!(
            "{field} name contains control characters"
        )));
    }
    Ok(())
}

/// Extract the array from a Resin list response: the `{"items":[...]}`
/// wrapper OR a bare array (Resin v1.2.0 uses both). Same contract as the
/// shell-side `commands::items_arr` — the canonical resin-core helper every
/// consumer in this crate routes through.
pub fn items_arr(v: &Value) -> &[Value] {
    if let Some(arr) = v.get("items").and_then(|i| i.as_array()) {
        return arr.as_slice();
    }
    if let Some(arr) = v.as_array() {
        return arr.as_slice();
    }
    &[]
}

/// Resin V1 platform-name rule, shared by every transport (
/// A-006: one validation, effective in both places). `create_platform_from_name`
/// applies it before the POST, and the headless BFF applies the SAME function to
/// `POST /api/v1/platforms`, so a browser caller cannot create a name the desktop
/// command would have refused.
pub fn validate_platform_name(name: &str) -> Result<(), String> {
    if name.trim().is_empty() {
        return Err("platform name cannot be empty".to_string());
    }
    if name.len() > 253 {
        return Err("platform name length > 253".to_string());
    }
    // Resin V1 rejects these characters and any whitespace. Mirroring the guard
    // here means the error comes from us, not an opaque 400.
    const BAD: &str = ".:|/\\@?#%~";
    if name.chars().any(|c| BAD.contains(c) || c.is_whitespace()) {
        return Err("platform name contains disallowed char".to_string());
    }
    Ok(())
}

/// Pure name→id lookup over a Resin list response (see items_arr for the
/// accepted shapes). A row whose `id` is missing/empty is skipped rather
/// than matched. Shared by the async `resolve_*_by_name` helpers and the
/// fn-pointer resolution seams in `strategy_service::apply`/`reconcile`
/// (whose signatures are wire-pinned by their mockito suites — the
/// single-GET two-step hop stays there).
pub fn resolve_id_in(v: &Value, want: &str) -> Option<String> {
    let rows: &[Value] = items_arr(v);
    for row in rows {
        let name = row.get("name").and_then(|n| n.as_str()).unwrap_or("");
        if name == want {
            let id = row.get("id").and_then(|n| n.as_str()).unwrap_or("");
            if !id.is_empty() {
                return Some(id.to_string());
            }
        }
    }
    None
}

/// Filter query for ResinClient::request_logs. Empty/None fields are omitted
/// from the query string. Cursor is Resin's opaque next-page token.
#[derive(Debug, Clone, Default)]
pub struct RequestLogQuery {
    pub platform_name: Option<String>,
    pub account: Option<String>,
    pub target_host: Option<String>,
    pub egress_ip: Option<String>,
    pub proxy_type: Option<String>,
    pub net_ok: Option<String>,
    pub http_status: Option<String>,
    pub cursor: Option<String>,
}

/// Fetch a Clash/ClashMeta subscription URL with a clash-family User-Agent.
///
/// Many subscription providers (the user's test host included) return 403 to a
/// default HTTP client UA but 200 + a full Clash YAML to a clash client UA.
/// We rotate a small pool of clash-family UAs so a single blocked UA string
/// does not make every subscription import fail. 15s timeout: subscription
/// YAML can be large (50+ proxies) on slow hosts.
///
/// Percent-encode a path segment or query value, keeping RFC 3986
/// alphanumerics plus `-`/`_` literal; every other UTF-8 byte becomes %XX.
/// Backed by the percent-encoding crate — no hand-rolled escape table.
/// (Resin IDs are canonical UUIDs and need no escaping, but we keep the
/// door open for future callers who might pass a name.)
const SEGMENT_ENCODE_SET: &percent_encoding::AsciiSet =
    &percent_encoding::NON_ALPHANUMERIC.remove(b'-').remove(b'_');

fn urlencoding(s: &str) -> String {
    percent_encoding::utf8_percent_encode(s, SEGMENT_ENCODE_SET).to_string()
}

/// JS encodeURIComponent unreserved set: A-Z a-z 0-9 - _ . ! ~ * ' ( ).
const URI_COMPONENT_ENCODE_SET: &percent_encoding::AsciiSet = &percent_encoding::NON_ALPHANUMERIC
    .remove(b'-')
    .remove(b'_')
    .remove(b'.')
    .remove(b'!')
    .remove(b'~')
    .remove(b'*')
    .remove(b'\'')
    .remove(b'(')
    .remove(b')');

/// encodeURIComponent-compatible path-segment encoder for account-header-rule
/// url_prefix values. The upstream contract test exercises
/// `api.example.com%2Fv1` — the `/` MUST stay percent-encoded so the Go 1.22
/// ServeMux `{prefix...}` wildcard receives one segment and unescapes it back
/// to `api.example.com/v1`. Byte-for-byte identical to JS
/// encodeURIComponent (same unreserved set, UTF-8 bytes) — the proven-good
/// encoding against this exact server.
fn encode_uri_component(s: &str) -> String {
    percent_encoding::utf8_percent_encode(s, URI_COMPONENT_ENCODE_SET).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_rejects_non_loopback() {
        assert!(ResinClient::new("http://10.0.0.1:2260", "tok".into()).is_err());
        assert!(ResinClient::new("http://example.com:2260", "tok".into()).is_err());
        assert!(ResinClient::new("http://169.254.169.254:2260", "tok".into()).is_err());
    }

    #[test]
    fn new_accepts_loopback_variants() {
        assert!(ResinClient::new("http://127.0.0.1:2260", "tok".into()).is_ok());
        assert!(ResinClient::new("http://localhost:2260", "tok".into()).is_ok());
        assert!(ResinClient::new("http://[::1]:2260", "tok".into()).is_ok());
    }

    #[test]
    fn urlencoding_escapes_disallowed_chars() {
        assert_eq!(urlencoding("foo-bar_b123"), "foo-bar_b123");
        assert_eq!(urlencoding("a/b"), "a%2Fb");
        // Non-ASCII input is UTF-8 percent-encoded per byte (the prior
        // char-wise table emitted the raw codepoint, e.g. %540D).
        assert_eq!(urlencoding("名"), "%E5%90%8D");
    }

    #[test]
    fn encode_uri_component_matches_js_unreserved_set() {
        assert_eq!(encode_uri_component("api.example.com/v1"), "api.example.com%2Fv1");
        // encodeURIComponent keeps - _ . ! ~ * ' ( ) literal.
        assert_eq!(encode_uri_component("a-b_c.d!e~f*g'h(i)"), "a-b_c.d!e~f*g'h(i)");
        assert_eq!(encode_uri_component("a b"), "a%20b");
    }

    #[tokio::test]
    async fn mockito_request_logs_happy_path_sends_limit() {
        // request_log_tail now tails GET /api/v1/request-logs?limit=N
        // instead of scanning Resin's private request_logs*.db files.
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"id":"ab","ts_ns":1727654400,"platform_name":"OpenAI","account":"k1","target_host":"api.openai.com","egress_ip":"1.2.3.4","proxy_type":"forward","net_ok":true,"http_method":"GET","http_status":200,"duration_ns":123456789,"resin_error":""}],"cursor":"","total":1}"#;
        let m = server
            .mock("GET", "/api/v1/request-logs")
            .match_header("authorization", "Bearer testtok")
            .match_query(mockito::Matcher::AllOf(vec![mockito::Matcher::UrlEncoded("limit".into(), "50".into())]))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .request_logs(50, None)
            .await
            .expect("request_logs should succeed against mockito");
        assert_eq!(out["items"][0]["platform_name"], "OpenAI");
        assert_eq!(out["items"][0]["http_status"], 200);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_request_logs_forwards_filters_and_encodes_them() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/request-logs")
            .match_header("authorization", "Bearer testtok")
            .match_query(mockito::Matcher::AllOf(vec![
                mockito::Matcher::UrlEncoded("limit".into(), "10".into()),
                mockito::Matcher::UrlEncoded("platform_name".into(), "OpenAI".into()),
                mockito::Matcher::UrlEncoded("account".into(), "a/b".into()),
                mockito::Matcher::UrlEncoded("target_host".into(), "api.openai.com".into()),
                mockito::Matcher::UrlEncoded("egress_ip".into(), "1.2.3.4".into()),
                mockito::Matcher::UrlEncoded("proxy_type".into(), "forward".into()),
                mockito::Matcher::UrlEncoded("net_ok".into(), "true".into()),
                mockito::Matcher::UrlEncoded("http_status".into(), "200".into()),
                mockito::Matcher::UrlEncoded("cursor".into(), "cur1".into()),
            ]))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{"items":[],"cursor":"","total":0}"#)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let q = RequestLogQuery {
            platform_name: Some("OpenAI".into()),
            account: Some("a/b".into()),
            target_host: Some("api.openai.com".into()),
            egress_ip: Some("1.2.3.4".into()),
            proxy_type: Some("forward".into()),
            net_ok: Some("true".into()),
            http_status: Some("200".into()),
            cursor: Some("cur1".into()),
        };
        c.request_logs(10, Some(&q))
            .await
            .expect("request_logs with filters should succeed");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_get_request_log_and_payloads_round_trip() {
        let mut server = mockito::Server::new_async().await;
        let m1 = server
            .mock("GET", "/api/v1/request-logs/log-1")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{"id":"log-1","ts_ns":1}"#)
            .create_async()
            .await;
        let m2 = server
            .mock("GET", "/api/v1/request-logs/log-1/payloads")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{"log_id":"log-1"}"#)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let one = c.get_request_log("log-1").await.expect("get_request_log");
        assert_eq!(one["id"], "log-1");
        let pl = c
            .get_request_log_payloads("log-1")
            .await
            .expect("get_request_log_payloads");
        assert_eq!(pl["log_id"], "log-1");
        m1.assert_async().await;
        m2.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_create_platform_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"name":"Platform-A","id":"11111111-1111-1111-1111-111111111111"}"#;
        let m = server
            .mock("POST", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .create_platform_from_name("Platform-A")
            .await
            .expect("create_platform_from_name should succeed against mockito");
        assert_eq!(out["name"], "Platform-A");
        assert_eq!(out["id"], "11111111-1111-1111-1111-111111111111");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_list_platforms_requires_bearer() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"[{"name":"Default","id":"00000000-0000-0000-0000-000000000000"}]"#;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .list_platforms()
            .await
            .expect("list_platforms should succeed");
        assert!(out.is_array());
        assert_eq!(out[0]["name"], "Default");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_delete_platform_204_no_content_round_trip() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("DELETE", "/api/v1/platforms/abc-123")
            .match_header("authorization", "Bearer testtok")
            .with_status(204)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .delete_platform("abc-123")
            .await
            .expect("delete_platform should succeed");
        assert!(out.is_null(), "204 No Content should parse to Value::Null");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn non_2xx_returns_err_with_status_and_excerpt() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms/missing")
            .match_header("authorization", "Bearer testtok")
            .with_status(404)
            .with_body(r#"{"error":"NOT_FOUND","detail":"no such platform"}"#)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c.get_platform("missing").await.unwrap_err().to_string();
        assert!(
            err.contains("404"),
            "error message must surface status: {err}"
        );
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_create_subscription_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"name":"sub-A","id":"22222222-2222-2222-2222-222222222222","source_type":"remote"}"#;
        let m = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .create_subscription(
                serde_json::json!({ "name": "sub-A", "url": "https://example.com/sub" }),
            )
            .await
            .expect("create_subscription should succeed against mockito");
        assert_eq!(out["name"], "sub-A");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_create_subscription_asserts_body_has_source_type_remote() {
        // the shell always posts source_type=remote for subscription_add;
        // Resin Scheduler re-pulls the URL on every refresh tick. Assert the body.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .match_body(mockito::Matcher::Regex(r#""source_type":"remote".*"#.to_string()))
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(r#"{"name":"sub-R","id":"33333333-3333-3333-3333-333333333333","source_type":"remote"}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let body = serde_json::json!({
            "name": "sub-R",
            "source_type": "remote",
            "url": "https://example.com/sub",
            "update_interval": "30s",
        });
        let out = c.create_subscription(body).await.expect("POST should succeed");
        assert_eq!(out["name"], "sub-R");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_delete_subscription_204_no_content_round_trip() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("DELETE", "/api/v1/subscriptions/abc-123")
            .match_header("authorization", "Bearer testtok")
            .with_status(204)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .delete_subscription("abc-123")
            .await
            .expect("delete_subscription should succeed");
        assert!(out.is_null(), "204 No Content should parse to Value::Null");
        m.assert_async().await;
    }

    // write-path 5xx retry (send_with_retry). POST /subscriptions
    // is the subscription_add transport; first attempt 503, second 201.
    #[tokio::test]
    async fn mockito_write_retry_503_then_201() {
        let mut server = mockito::Server::new_async().await;
        let m503 = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(503)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"transient"}"#)
            .expect(1)
            .create_async()
            .await;
        let m201 = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(
                r#"{"name":"sub-retry","id":"44444444-4444-4444-4444-444444444444","source_type":"remote"}"#,
            )
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .create_subscription(serde_json::json!({
                "name": "sub-retry",
                "url": "https://example.com/sub"
            }))
            .await
            .expect("POST should succeed on the retried attempt");
        assert_eq!(out["name"], "sub-retry");
        m503.assert_async().await;
        m201.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_write_retry_exhausts_after_three_attempts() {
        // 3 attempts (initial + 2 retries) all 500 -> error surfaced, 3 hits.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(500)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"down"}"#)
            .expect(3)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c
            .create_subscription(serde_json::json!({
                "name": "sub-x",
                "url": "https://example.com/sub"
            }))
            .await
            .expect_err("persistent 500 must surface after 2 retries");
        assert!(
            format!("{err}").contains("-> 500"),
            "error should carry the upstream status: {err}"
        );
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_write_4xx_never_retried() {
        // 4xx is a client error (e.g. Resin's update_interval >= 30s contract
        // rejecting a below-floor value with 400): exactly one hit, no retry.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(400)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"update_interval: must be >= 30s"}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c
            .create_subscription(serde_json::json!({
                "name": "sub-fast",
                "url": "https://example.com/sub",
                "update_interval": "5s"
            }))
            .await
            .expect_err("400 must fail without retry");
        assert!(
            format!("{err}").contains("-> 400"),
            "error should carry the upstream status: {err}"
        );
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_subscription_update_interval_three_states_wire_contract() {
// F3: Resin parses update_interval as a Go time.Duration and
        // enforces >= 30s (resin/internal/service/control_plane_subscription.go
        // minSubscriptionUpdateInterval, create AND PATCH paths). Wire contract
        // at the shell boundary: 30s and 1m pass through and are accepted; 5s
        // is rejected 400 by Resin and the write-retry must NOT re-POST a
        // rejected body (4xx never retries).
        let mut server = mockito::Server::new_async().await;
        let m30 = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .match_body(mockito::Matcher::Regex(r#""update_interval":"30s""#.to_string()))
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(r#"{"name":"sub-30s","id":"55555555-5555-5555-5555-555555555555"}"#)
            .expect(1)
            .create_async()
            .await;
        let m1m = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .match_body(mockito::Matcher::Regex(r#""update_interval":"1m""#.to_string()))
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(r#"{"name":"sub-1m","id":"66666666-6666-6666-6666-666666666666"}"#)
            .expect(1)
            .create_async()
            .await;
        let m5s = server
            .mock("POST", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .match_body(mockito::Matcher::Regex(r#""update_interval":"5s""#.to_string()))
            .with_status(400)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"update_interval: must be >= 30s"}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        c.create_subscription(serde_json::json!({
            "name": "sub-30s", "url": "https://e.com/a", "update_interval": "30s"
        }))
        .await
        .expect("30s is Resin's enforced floor: accepted");
        c.create_subscription(serde_json::json!({
            "name": "sub-1m", "url": "https://e.com/b", "update_interval": "1m"
        }))
        .await
        .expect("1m above floor: accepted");
        let err = c
            .create_subscription(serde_json::json!({
                "name": "sub-5s", "url": "https://e.com/c", "update_interval": "5s"
            }))
            .await
            .expect_err("5s below Resin's >=30s floor: rejected");
        assert!(format!("{err}").contains("-> 400"));
        m30.assert_async().await;
        m1m.assert_async().await;
        m5s.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_update_platform_patches_allocation_policy() {

        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"11111111-1111-1111-1111-111111111111","name":"OpenAI","allocation_policy":"PREFER_LOW_LATENCY"}"#;
        let m = server
            .mock(
                "PATCH",
                "/api/v1/platforms/11111111-1111-1111-1111-111111111111",
            )
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .match_body(mockito::Matcher::PartialJson(
                serde_json::json!({"allocation_policy":"PREFER_LOW_LATENCY"}),
            ))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .update_platform(
                "11111111-1111-1111-1111-111111111111",
                serde_json::json!({"allocation_policy":"PREFER_LOW_LATENCY"}),
            )
            .await
            .expect("update_platform should succeed against mockito");
        assert_eq!(out["allocation_policy"], "PREFER_LOW_LATENCY");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_list_nodes_returns_items_wrapper() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"name":"sg-01","type":"trojan","egress_ip":"1.2.3.4"}],"total":1,"limit":50,"offset":0,"unique_egress_ips":1,"unique_healthy_egress_ips":1}"#;
        let m = server
            .mock("GET", "/api/v1/nodes?limit=500")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .list_nodes()
            .await
            .expect("list_nodes should succeed against mockito");
        assert_eq!(out["total"], 1);
        assert_eq!(out["items"][0]["egress_ip"], "1.2.3.4");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_list_nodes_for_platform_passes_platform_id_query() {
        let mut server = mockito::Server::new_async().await;
        let pid = "22222222-2222-2222-2222-222222222222";
        let body = r#"{"items":[{"node_hash":"a","display_tag":"hk-01","has_outbound":true,"failure_count":0,"region":"hk","tags":[]}],"total":1,"limit":500,"offset":0}"#;
        let m = server
            .mock("GET", mockito::Matcher::Any)
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .list_nodes_for_platform(pid)
            .await
            .expect("list_nodes_for_platform should succeed against mockito");
        assert_eq!(out["total"], 1);
        assert_eq!(out["items"][0]["display_tag"], "hk-01");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_create_platform_with_fields_full_schema() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"44444444-4444-4444-4444-444444444444","name":"auto-ab12cd34","allocation_policy":"BALANCED","routable_node_count":0}"#;
        let m = server
            .mock("POST", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .create_platform_with_fields(serde_json::json!({
                "name": "auto-ab12cd34",
                "allocation_policy": "BALANCED",
                "region_filters": ["hk"],
            }))
            .await
            .expect("create_platform_with_fields should succeed against mockito");
        assert_eq!(out["name"], "auto-ab12cd34");
        assert_eq!(out["allocation_policy"], "BALANCED");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_platform_leases_items_wrapper() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"platform_id":"abc","account":"f00dface","node_hash":"9f2c0b1a6d3e4f5c8a9b0c1d2e3f4a5b","egress_ip":"5.6.7.8","expiry":"2026-02-10T13:00:00Z","last_accessed":"2026-02-10T12:59:50Z"}],"total":1,"limit":50,"offset":0}"#;
        let m = server
            .mock("GET", "/api/v1/platforms/abc/leases")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .platform_leases("abc")
            .await
            .expect("platform_leases should succeed against mockito");
        assert_eq!(out["total"], 1);
        assert_eq!(out["items"][0]["account"], "f00dface");
        assert_eq!(out["items"][0]["egress_ip"], "5.6.7.8");
        m.assert_async().await;
    }


    // ── Endpoint API mockito tests (Resin v1.2.0) ────────────────────

    #[tokio::test]
    async fn mockito_list_endpoints_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"id":"default","port":2260,"allow_management":true,"allow_proxy":true,"source":"environment","read_only":true}]}"#;
        let m = server
            .mock("GET", "/api/v1/endpoints")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c.list_endpoints().await.expect("list_endpoints should succeed");
        assert!(out["items"].is_array());
        assert_eq!(out["items"][0]["id"], "default");
        assert_eq!(out["items"][0]["port"], 2260);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_create_endpoint_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"abc123","port":17990,"allow_management":false,"allow_proxy":true}"#;
        let m = server
            .mock("POST", "/api/v1/endpoints")
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let req = serde_json::json!({"port":17990,"allow_proxy":true,"allow_socks5":true});
        let out = c.create_endpoint(req).await.expect("create_endpoint should succeed");
        assert_eq!(out["id"], "abc123");
        assert_eq!(out["port"], 17990);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_update_endpoint_patch() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"abc123","port":17991,"allow_proxy":true}"#;
        let m = server
            .mock("PATCH", "/api/v1/endpoints/abc123")
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let req = serde_json::json!({"port":17991});
        let out = c.update_endpoint("abc123", req).await.expect("update_endpoint should succeed");
        assert_eq!(out["port"], 17991);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_delete_endpoint_204() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("DELETE", "/api/v1/endpoints/abc123")
            .match_header("authorization", "Bearer testtok")
            .with_status(204)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c.delete_endpoint("abc123").await.expect("delete_endpoint should succeed");
        // 204 no content -> empty Value
        assert!(out.is_null() || out.is_object());
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_get_endpoint_single() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"id":"default","port":2260,"allow_socks5":true,"source":"environment","read_only":true}"#;
        let m = server
            .mock("GET", "/api/v1/endpoints/default")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c.get_endpoint("default").await.expect("get_endpoint should succeed");
        assert_eq!(out["id"], "default");
        assert_eq!(out["port"], 2260);
        assert_eq!(out["source"], "environment");
        assert_eq!(out["read_only"], true);
        m.assert_async().await;
    }


    #[tokio::test]
    async fn mockito_read_retry_503_then_200() {
        // First call returns 503, second returns 200 (send_read retries up to 2 times)
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"name":"retry-test"}],"total":1}"#;
        let m503 = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(503)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"transient"}"#)
            .expect(1)
            .create_async()
            .await;
        let m200 = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c.list_platforms().await.expect("list_platforms should succeed after retry");
        assert_eq!(out["items"][0]["name"], "retry-test");
        // First attempt (503) + second attempt (200) = 2 hits total
        m503.assert_async().await;
        m200.assert_async().await;


    }

    #[tokio::test]
    async fn mockito_read_retry_all_503_exhausts() {
        // All 3 attempts return 503 -> error is surfaced
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(503)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"transient"}"#)
            .expect(3)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let result = c.list_platforms().await;
        assert!(result.is_err(), "should error after exhausting retries");
        // 1 initial + 2 retries = 3 total attempts
        m.assert_async().await;

    }

    #[tokio::test]
    async fn mockito_read_no_retry_on_4xx() {
        // 404 should NOT retry (4xx is not transient)
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(404)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"not found"}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
       let result = c.list_platforms().await;
       assert!(result.is_err(), "404 should error without retry");
       // Should be called exactly once (no retry on 4xx)
       m.assert_async().await;

   }

    #[tokio::test]
    async fn mockito_refresh_subscription_native_posts_actions_refresh() {
        // POST /api/v1/subscriptions/{id}/actions/refresh (no body) -> 200 {}.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("POST", "/api/v1/subscriptions/sub-uuid-1/actions/refresh")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .refresh_subscription_native("sub-uuid-1")
            .await
            .expect("refresh_subscription_native should succeed");
        assert!(out.is_object() || out.is_null(), "200 with empty body is acceptable");
        m.assert_async().await;
    }

   #[tokio::test]
   async fn mockito_probe_node_egress_returns_egress_ip_region_latency() {
       // POST /nodes/{hash}/actions/probe-egress -> {egress_ip, region, latency_ewma_ms}.
       let mut server = mockito::Server::new_async().await;
       let m = server
           .mock("POST", "/api/v1/nodes/abc123/actions/probe-egress")
           .match_header("authorization", "Bearer testtok")
           .with_status(200)
           .with_header("content-type", "application/json")
           .with_body(r#"{"egress_ip":"203.0.113.1","region":"us","latency_ewma_ms":123.45}"#)
           .expect(1)
           .create_async()
           .await;
       let base = server.url();
       let c = ResinClient::new(&base, "testtok".into()).unwrap();
       let out = c
           .probe_node_egress("abc123")
           .await
           .expect("probe_node_egress should succeed");
       assert_eq!(out["egress_ip"], "203.0.113.1");
       assert_eq!(out["region"], "us");
       assert_eq!(out["latency_ewma_ms"], 123.45);
       m.assert_async().await;
   }

   #[tokio::test]
   async fn mockito_probe_node_latency_returns_latency_ewma_ms() {
       // POST /nodes/{hash}/actions/probe-latency -> {latency_ewma_ms}.
       let mut server = mockito::Server::new_async().await;
       let m = server
           .mock("POST", "/api/v1/nodes/abc123/actions/probe-latency")
           .match_header("authorization", "Bearer testtok")
           .with_status(200)
           .with_header("content-type", "application/json")
           .with_body(r#"{"latency_ewma_ms":89.12}"#)
           .expect(1)
           .create_async()
           .await;
       let base = server.url();
       let c = ResinClient::new(&base, "testtok".into()).unwrap();
       let out = c
           .probe_node_latency("abc123")
           .await
           .expect("probe_node_latency should succeed");
       assert_eq!(out["latency_ewma_ms"], 89.12);
       m.assert_async().await;
   }

    // ── Account header rules mockito tests ─────

    #[tokio::test]
    async fn mockito_list_account_header_rules_happy_path() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"url_prefix":"api.example.com/v1","headers":["Authorization"],"updated_at":"2026-09-04T00:00:00Z"}],"total":1,"limit":1000,"offset":0}"#;
        let m = server
            .mock("GET", "/api/v1/account-header-rules?limit=1000&offset=0")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .list_account_header_rules(None)
            .await
            .expect("list_account_header_rules should succeed");
        assert_eq!(out["total"], 1);
        assert_eq!(out["items"][0]["url_prefix"], "api.example.com/v1");
        assert_eq!(out["items"][0]["headers"][0], "Authorization");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_list_account_header_rules_keyword_filter() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"items":[{"url_prefix":"files.example.com/v2","headers":["X-Trace-Id"],"updated_at":"2026-09-04T00:00:00Z"}],"total":1,"limit":1000,"offset":0}"#;
        let m = server
            .mock("GET", "/api/v1/account-header-rules?limit=1000&offset=0&keyword=trace")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        // keyword is trimmed by the wrapper: " trace " -> "trace".
        let out = c
            .list_account_header_rules(Some(" trace "))
            .await
            .expect("keyword list should succeed");
        assert_eq!(out["items"][0]["url_prefix"], "files.example.com/v2");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_put_account_header_rules_created_201() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"url_prefix":"api.example.com/v1","headers":["Authorization"],"updated_at":"2026-09-04T00:00:00Z"}"#;
        let m = server
            .mock("PUT", "/api/v1/account-header-rules/api.example.com%2Fv1")
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .match_body(r#"{"headers":["Authorization"]}"#)
            .with_status(201)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .put_account_header_rules("api.example.com/v1", &["Authorization".to_string()])
            .await
            .expect("put_account_header_rules should succeed");
        assert_eq!(out["url_prefix"], "api.example.com/v1");
        assert_eq!(out["headers"][0], "Authorization");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_put_account_header_rules_400_invalid_header() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("PUT", "/api/v1/account-header-rules/api.example.com%2Fv1")
            .match_header("authorization", "Bearer testtok")
            .with_status(400)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"invalid_argument","message":"headers[0]: \"bad header\" is not a valid HTTP header name (RFC 7230 token)"}"#)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c
            .put_account_header_rules("api.example.com/v1", &["bad header".to_string()])
            .await
            .expect_err("invalid header name must surface the upstream 400");
        assert!(err.to_string().contains("400"), "error carries status: {err}");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_resolve_account_header_rule_matched() {
        let mut server = mockito::Server::new_async().await;
        let body = r#"{"matched_url_prefix":"api.example.com","headers":["Authorization"]}"#;
        let m = server
            .mock("POST", "/api/v1/account-header-rules:resolve")
            .match_header("authorization", "Bearer testtok")
            .match_header("content-type", "application/json")
            .match_body(mockito::Matcher::Regex(r#""url":"https://api.example.com/v1/chat".*"#.to_string()))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(body)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .resolve_account_header_rule("https://api.example.com/v1/chat")
            .await
            .expect("resolve_account_header_rule should succeed");
        assert_eq!(out["matched_url_prefix"], "api.example.com");
        assert_eq!(out["headers"][0], "Authorization");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_resolve_account_header_rule_no_match_empty() {
        let mut server = mockito::Server::new_async().await;
        // No rule matched: 200 with empty fields, NOT an error (control_plane_rules.go:167-169).
        let m = server
            .mock("POST", "/api/v1/account-header-rules:resolve")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{"matched_url_prefix":"","headers":[]}"#)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .resolve_account_header_rule("https://unmatched.example.org/x")
            .await
            .expect("no-match resolve is a 200 result");
        assert_eq!(out["matched_url_prefix"], "");
        assert_eq!(out["headers"].as_array().map(|a| a.len()), Some(0));
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_delete_account_header_rule_204_null() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("DELETE", "/api/v1/account-header-rules/files.example.com%2Fv2")
            .match_header("authorization", "Bearer testtok")
            .with_status(204)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .delete_account_header_rule("files.example.com/v2")
            .await
            .expect("delete_account_header_rule should succeed");
        assert!(out.is_null(), "204 no content -> Null, got {out}");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_delete_account_header_rule_404_not_found() {
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("DELETE", "/api/v1/account-header-rules/missing.example.com")
            .match_header("authorization", "Bearer testtok")
            .with_status(404)
            .with_header("content-type", "application/json")
            .with_body(r#"{"error":"not_found","message":"rule not found"}"#)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c
            .delete_account_header_rule("missing.example.com")
            .await
            .expect_err("unknown rule surfaces the upstream 404");
        assert!(err.to_string().contains("404"), "error carries status: {err}");
        m.assert_async().await;
    }

   #[test]
   fn shared_client_returns_same_instance() {
        // Two calls to shared_client() must return pointers to the same Client.
        let a = shared_client();
        let b = shared_client();
        // Pointer equality: same address = same Client
        assert!(std::ptr::eq(a, b), "shared_client() returned different Client instances");
    }

    // ── name→UUID resolution helpers ──────────

    #[tokio::test]
    async fn mockito_resolve_platform_id_by_name_hit() {
        // Hit: name exists in the items-wrapper list -> the UUID.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{"items":[{"id":"plat-uuid-1","name":"alpha","region_filters":["US"]}],"total":1}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let id = c
            .resolve_platform_id_by_name("alpha")
            .await
            .expect("resolve_platform_id_by_name hit should return the id");
        assert_eq!(id, "plat-uuid-1");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_resolve_platform_id_by_name_miss_is_not_found() {
        // Miss: name absent -> typed IpcError::NotFound with the
        // same message text the former stringly rejection produced.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{"items":[{"id":"plat-uuid-2","name":"beta"}],"total":1}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c
            .resolve_platform_id_by_name("ghost")
            .await
            .expect_err("miss should error");
        assert!(
            matches!(
                &err,
                IpcError::NotFound { msg, i18n_key }
                    if msg == "platform not found: ghost" && i18n_key == "error.notFound"
            ),
            "got {err:?}"
        );
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_resolve_platform_id_by_name_non_json_is_internal() {
        // Parse failure: a 200 whose application/json body does
        // not decode -> send() errors and map_resin_error surfaces the
        // Internal catch-all (the enum has no Backend variant; the issue
        // draft's "Backend" maps here — see report deviation note).
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/platforms")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body("this is not json{")
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c
            .resolve_platform_id_by_name("alpha")
            .await
            .expect_err("malformed body should error");
        assert!(matches!(err, IpcError::Internal { .. }), "got {err:?}");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_resolve_subscription_id_by_name_hit() {
        // Hit, subscription face. Bare-array responses resolve
        // too (the same mixed-shape contract the shell items_arr handled).
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"[{"id":"sub-uuid-7","name":"main","node_count":12}]"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let id = c
            .resolve_subscription_id_by_name("main")
            .await
            .expect("resolve_subscription_id_by_name hit should return the id");
        assert_eq!(id, "sub-uuid-7");
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_resolve_subscription_id_by_name_miss_is_not_found() {
        // Miss, subscription face: absent name AND the
        // empty-id-row skip (a matched row without an id cannot resolve).
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(
                r#"[{"id":"","name":"empty-id"},{"name":"no-id-field"},{"id":"sub-uuid-8","name":"other"}]"#,
            )
            .expect(3)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        for want in ["empty-id", "no-id-field", "ghost"] {
            let err = c
                .resolve_subscription_id_by_name(want)
                .await
                .expect_err("unresolvable name should error");
            assert!(
                matches!(
                    &err,
                    IpcError::NotFound { msg, i18n_key }
                        if *msg == format!("subscription not found: {want}")
                            && i18n_key == "error.notFound"
                ),
                "want={want} got {err:?}"
            );
        }
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_resolve_subscription_id_by_name_non_json_is_internal() {
        // Parse failure, subscription face.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/subscriptions")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body("<html>oops</html>")
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let err = c
            .resolve_subscription_id_by_name("main")
            .await
            .expect_err("malformed body should error");
        assert!(matches!(err, IpcError::Internal { .. }), "got {err:?}");
        m.assert_async().await;
    }

    #[test]
    fn resolve_helpers_reject_bad_names_before_any_http() {
        // F3/§7.5: DNS-host length cap (253) + NUL/control rejection, both
        // surfacing as IpcError::InvalidInput (never a panic). Validation
        // fires before the list GET, so no mockito server is even needed.
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();
        let c = ResinClient::new("http://127.0.0.1:1", "tok".into()).unwrap();
        for name in [
            "",                                  // empty
            &"a".repeat(254),                    // over the 253 cap
            "bad\0nul",                          // NUL
            "bad\nnewline",                      // control char
            "bad\u{7f}del",                      // DEL
        ] {
            for helper in ["platform", "subscription"] {
                let err = if helper == "platform" {
                    rt.block_on(async { c.resolve_platform_id_by_name(name).await.err().unwrap() })
                } else {
                    rt.block_on(async { c.resolve_subscription_id_by_name(name).await.err().unwrap() })
                };
                assert!(
                    matches!(&err, IpcError::InvalidInput { .. }),
                    "name={name:?} helper={helper} got {err:?}"
                );
            }
        }
    }

    #[test]
    fn resolve_id_in_semantics_lock() {
        // Pure resolver contract: items-wrapper OR bare array, first
        // name match with a NON-empty id, no row -> None.
        let wrapper = serde_json::json!({
            "items": [
                {"id": "", "name": "dup"},
                {"id": "second", "name": "dup"},
                {"id": "third", "name": "other"},
            ],
            "total": 3,
        });
        assert_eq!(
            resolve_id_in(&wrapper, "dup"),
            Some("second".to_string()),
            "empty-id rows are skipped, a later same-name row still resolves"
        );
        let bare = serde_json::json!([{"id": "x1", "name": "solo"}]);
        assert_eq!(resolve_id_in(&bare, "solo"), Some("x1".to_string()));
        assert_eq!(resolve_id_in(&bare, "absent"), None);
        // A non-list object (unexpected backend shape) resolves nothing.
        assert_eq!(resolve_id_in(&serde_json::json!({"foo": 1}), "x"), None);
        assert_eq!(resolve_id_in(&Value::Null, "x"), None);
    }
    // ── metrics minimal-set mockito tests (ADR-0064) ─────────────

    #[tokio::test]
    async fn mockito_realtime_throughput_happy_path_no_params() {
        // The shell sends no from/to; Resin's parseMetricsTimeRange defaults
        // apply upstream (to=now, from=to-1h). Assert the path has no query.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", "/api/v1/metrics/realtime/throughput")
            .match_header("authorization", "Bearer testtok")
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(
                r#"{"step_seconds":10,"items":[{"ts":"2026-09-04T00:00:00Z","ingress_bps":1200,"egress_bps":3400}]}"#,
            )
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .realtime_throughput()
            .await
            .expect("realtime_throughput should succeed against mockito");
        assert_eq!(out["step_seconds"], 10);
        assert_eq!(out["items"][0]["ingress_bps"], 1200);
        assert_eq!(out["items"][0]["egress_bps"], 3400);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_probe_history_sends_rfc3339_from_to() {
        // from/to arrive at this layer as RFC3339Nano strings already
        // boundary-validated by the IPC layer; assert they ride the query
        // string URL-encoded (`:` is escaped by the shared urlencoding helper).
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", mockito::Matcher::Any)
            .match_header("authorization", "Bearer testtok")
            .match_query(mockito::Matcher::AllOf(vec![
                mockito::Matcher::UrlEncoded("from".into(), "2026-09-04T00:00:00Z".into()),
                mockito::Matcher::UrlEncoded("to".into(), "2026-09-04T01:00:00Z".into()),
            ]))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(
                r#"{"bucket_seconds":60,"items":[{"bucket_start":"2026-09-04T00:00:00Z","bucket_end":"2026-09-04T00:01:00Z","total_count":3}]}"#,
            )
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .probe_history(Some("2026-09-04T00:00:00Z"), Some("2026-09-04T01:00:00Z"))
            .await
            .expect("probe_history should succeed against mockito");
        assert_eq!(out["bucket_seconds"], 60);
        assert_eq!(out["items"][0]["total_count"], 3);
        m.assert_async().await;
    }

    #[tokio::test]
    async fn mockito_probe_history_without_to_omits_param() {
        // to=None must not append an empty &to= — Resin then applies its
        // to=now default. Match on the from param only.
        let mut server = mockito::Server::new_async().await;
        let m = server
            .mock("GET", mockito::Matcher::Any)
            .match_header("authorization", "Bearer testtok")
            .match_query(mockito::Matcher::AllOf(vec![mockito::Matcher::UrlEncoded("from".into(), "2026-09-04T00:00:00Z".into())]))
            .with_status(200)
            .with_header("content-type", "application/json")
            .with_body(r#"{"bucket_seconds":60,"items":[]}"#)
            .expect(1)
            .create_async()
            .await;
        let base = server.url();
        let c = ResinClient::new(&base, "testtok".into()).unwrap();
        let out = c
            .probe_history(Some("2026-09-04T00:00:00Z"), None)
            .await
            .expect("probe_history without to should succeed");
        assert_eq!(out["items"], serde_json::json!([]));
        m.assert_async().await;
    }
    #[test]
    fn validate_platform_name_mirrors_the_resin_v1_rule() {
        // (A-006): the shared rule the headless BFF also applies.
        for ok in ["openai", "auto-ab12cd34", "p1"] {
            assert!(validate_platform_name(ok).is_ok(), "{ok} should pass");
        }
        for bad in ["", "   ", "a b", "a.b", "a:b", "a|b", "a/b", "a\\b", "a@b", "a?b", "a#b", "a%b", "a~b"] {
            assert!(validate_platform_name(bad).is_err(), "{bad:?} should be rejected");
        }
        let long = "a".repeat(254);
        assert!(validate_platform_name(&long).is_err(), "over 253 chars");
        let max = "a".repeat(253);
        assert!(validate_platform_name(&max).is_ok(), "exactly 253 chars");
    }
}
