// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	setLogLevel: (level: LogLevel) => typedError<string, IpcError>(__TAURI_INVOKE("set_log_level", { level })),
	/**
	 *  T18-S2 (ADR-0042): Toggle enabled flag on an entry-port without
	 *  re-POST/Create or DELETE. Patches the Resin endpoint `{enabled: bool}`
	 *  (Resin v1.2.0 supports `enabled` on PATCH — `inactive` keeps the record)
	 *  then persists the same flag into the shell whitebox `entry_ports[].enabled`
	 *  so the whitebox is the authoritative record. The listener is NOT removed
	 *  from Resin's DB when toggled off, so toggled back on is a PATCH only.
	 */
	portToggle: (port: number, enabled: boolean) => typedError<PortMapping, IpcError>(__TAURI_INVOKE("port_toggle", { port, enabled })),
};

/* Types */
/**  Typed IPC error returned by every Tauri command. */
export type IpcError = 
/**  Port number already in use (EADDRINUSE / Resin 409 bind conflict). */
{ kind: "BindConflict"; data: {
	port: number,
	i18n_key: string,
} } | 
/**  Strategy value rejected by the Rust-side catalog. */
{ kind: "InvalidStrategy"; data: {
	value: string,
	accepted: string[],
	i18n_key: string,
} } | 
/**  Resin sidecar returned a non-2xx status. */
{ kind: "ResinUpstream"; data: {
	status: number,
	excerpt: string,
	i18n_key: string,
} } | 
/**  Catch-all for internal errors (serde, IO, unexpected panic recovery). */
{ kind: "Internal"; data: {
	msg: string,
	i18n_key: string,
} };

/**
 *  Ticket 09 (tauri-specta pilot): log level as a closed enum. The wire
 *  format is unchanged (lowercase string, serde rename_all); out-of-set
 *  values are now rejected by serde at deserialization instead of the
 *  former in-command String match. Exported into src/bindings.ts so the
 *  frontend narrows against the generated union.
 */
export type LogLevel = "error" | "warn" | "info" | "debug";

/**  One row of the port_mappings table. */
export type PortMapping = {
	port: number,
	protocol: string,
	platform_name: string,
	account: string,
	label: string,
	enabled: boolean,
	auth_required: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

